let state=null,room=localStorage.fr7room||'',myId=localStorage.fr7pid||'',lastReactionId=null,reactionTimer=null;const $=id=>document.getElementById(id);
async function api(path,data={}){let url='/api/'+path,opt={method:path==='state'?'GET':'POST',headers:{'Content-Type':'application/json'}};if(path==='state')url+='?'+new URLSearchParams({room,playerId:myId});else{let p={...data};if(!['create','join'].includes(path)){p.room=room;p.playerId=myId}opt.body=JSON.stringify(p)}let r=await fetch(url,opt),j=await r.json();if(!j.ok)throw Error(j.error);if(j.state)render(j.state);return j}
function enter(){$('home').classList.add('hidden');$('game').classList.remove('hidden')}
$('create').onclick=async()=>{try{let r=await api('create',{name:$('name').value||'Host'});room=r.room;myId=r.playerId;localStorage.fr7room=room;localStorage.fr7pid=myId;enter();render(r.state)}catch(e){$('err').textContent=e.message}}
$('join').onclick=async()=>{try{let r=await api('join',{name:$('name').value||'Player',room:$('roomCode').value});room=r.room;myId=r.playerId;localStorage.fr7room=room;localStorage.fr7pid=myId;enter();render(r.state)}catch(e){$('err').textContent=e.message}}
for(const [id,p] of [['hit','hit'],['stay','stay'],['start','start'],['next','next']])$(id).onclick=()=>api(p).catch(e=>alert(e.message));$('leave').onclick=()=>{localStorage.removeItem('fr7room');localStorage.removeItem('fr7pid');location.reload()}
function preview(p){if(!p||p.busted)return 0;let n=p.cards.reduce((s,c)=>s+c.value,0);if(p.mods.some(c=>c.type==='multiplier'))n*=2;n+=p.mods.filter(c=>c.type==='modifier').reduce((s,c)=>s+c.value,0);if(p.cards.length>=7)n+=15;return n}
function card(c){let cls='card';let txt='';if(c.type==='number')txt=c.value;else if(c.type==='modifier'){txt='+'+c.value;cls+=' mod'}else if(c.type==='multiplier'){txt='×2';cls+=' mult'}else{txt=c.name==='freeze'?'FREEZE':c.name==='flip3'?'FLIP THREE':'SECOND CHANCE';cls+=' action '+c.name}return `<div class="${cls}">${txt}</div>`}
function renderTarget(s){let a=s.pendingAction;if(!a||a.chooserId!==myId){$('target').classList.add('hidden');return}let eligible=s.players.filter(p=>a.eligibleIds.includes(p.id));let title=a.kind==='secondTransfer'?'Give the extra SECOND CHANCE to:':a.kind==='freeze'?'Choose who receives FREEZE:':'Choose who must FLIP THREE:';$('target').innerHTML=`<b>${title}</b><div class="targetlist">${eligible.map(p=>`<button class="secondary" data-id="${p.id}">${p.id===myId?'Yourself':p.name}</button>`).join('')}</div>`;$('target').classList.remove('hidden');$('target').querySelectorAll('button').forEach(b=>b.onclick=()=>api('target',{targetId:b.dataset.id}).catch(e=>alert(e.message)))}
function sendReaction(kind,value){api('react',{kind,value}).catch(e=>alert(e.message));$('reactionMenu').classList.add('hidden')}
$('reactionToggle').onclick=()=>$('reactionMenu').classList.toggle('hidden');
document.querySelectorAll('[data-emoji]').forEach(b=>b.onclick=()=>sendReaction('emoji',b.dataset.emoji));
document.querySelectorAll('[data-phrase]').forEach(b=>b.onclick=()=>sendReaction('phrase',b.dataset.phrase));
function showReaction(r){if(!r||r.id===lastReactionId)return;lastReactionId=r.id;const o=$('reactionOverlay');$('reactionName').textContent=r.playerName+' says';$('reactionText').textContent=r.value;o.classList.remove('hidden','show','emoji');if(r.kind==='emoji')o.classList.add('emoji');void o.offsetWidth;o.classList.add('show');clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>{o.classList.add('hidden');o.classList.remove('show','emoji')},2700)}
function render(s){state=s;showReaction(s.reaction);$('code').textContent=s.code;$('round').textContent=s.round;let me=s.players.find(p=>p.id===myId),turn=s.players[s.turnIndex];$('players').innerHTML=s.players.map((p,i)=>`<div class="player ${s.phase==='playing'&&!s.pendingAction&&i===s.turnIndex?'turn':''}"><b>${p.name}${p.id===s.hostId?' ★':''}</b><br><small>${p.busted?'BUST':p.frozen?'FROZEN':p.stayed?'STAYED':preview(p)+' this round'}${p.second?' · 2ND CHANCE':''}</small><div>Score: <b>${p.score}</b></div></div>`).join('');$('lobby').classList.toggle('hidden',s.phase!=='lobby');$('table').classList.toggle('hidden',s.phase==='lobby');$('lobby').innerHTML=`Waiting for players (${s.players.length}/9). Official game requires 3–9 players.`;$('myhand').innerHTML=me?[...me.cards,...me.mods,...(me.second?[{type:'action',name:'second'}]:[])].map(card).join(''):'';$('value').textContent=preview(me);renderTarget(s);let myTurn=s.phase==='playing'&&!s.pendingAction&&turn?.id===myId;$('hit').disabled=!myTurn;$('stay').disabled=!myTurn;$('hit').classList.toggle('hidden',s.phase!=='playing'||!!s.pendingAction);$('stay').classList.toggle('hidden',s.phase!=='playing'||!!s.pendingAction);$('start').classList.toggle('hidden',!(s.phase==='lobby'&&s.hostId===myId));$('next').classList.toggle('hidden',!(s.phase==='roundEnd'&&s.hostId===myId));$('status').textContent=s.pendingAction?(s.pendingAction.chooserId===myId?'Choose a target':'Another player is choosing a target'):s.phase==='lobby'?'Waiting for players':s.phase==='playing'?(myTurn?'Your turn — Flip or Stay':(turn?.name||'')+"'s turn"):s.phase==='roundEnd'?'Round complete':s.winner+' wins!';$('log').innerHTML=s.log.map(x=>'<div>'+x+'</div>').join('')}
if(room&&myId){enter();api('state').catch(()=>{})}setInterval(()=>{if(room&&myId)api('state').catch(()=>{})},900);