let state=null,myId=localStorage.fr7pid||'',room=localStorage.fr7room||'',lastCardCount=0,lastPhase='',soundOn=localStorage.fr7sound!=='off',pollFailures=0,reactionTimer=null,phraseTimer=null;
const seenReactions=new Set(),seenPhrases=new Set();
const QUICK_PHRASES=['Nice Job!',"You're almost there!",'So Close!','You suck!','Oh Man!'];
const BECCA_PHRASE="You're a peckerhead!";
const $=id=>document.getElementById(id),home=$('home'),game=$('game'),err=$('error');
const avatarColors=['#32e5cb','#ffdd42','#ff6f91','#8e7dff','#ff914d','#72d7ff'];
function haptic(ms=18){if(navigator.vibrate)navigator.vibrate(ms)}
function tone(freq=440,duration=.08,type='sine',gain=.05){if(!soundOn)return;try{const C=window.AudioContext||window.webkitAudioContext,a=new C(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.stop(a.currentTime+duration)}catch{}}
async function api(path,data={}){try{const isState=path==='state';let url='/api/'+path;const options={method:isState?'GET':'POST',headers:{'Content-Type':'application/json'}};if(isState){const params=new URLSearchParams({room,playerId:myId});url+='?'+params.toString()}else{const payload={...data};if(path!=='create'&&path!=='join'){payload.room=room;payload.playerId=myId}options.body=JSON.stringify(payload)}const response=await fetch(url,options);const json=await response.json();if(!json.ok)throw new Error(json.error);pollFailures=0;$('connection').classList.add('hidden');if(json.state)render(json.state);return json}catch(e){pollFailures++;if(pollFailures>2&&room)$('connection').classList.remove('hidden');throw e}}
function enter(){home.classList.remove('active');game.classList.add('active')}
function leave(){localStorage.removeItem('fr7room');localStorage.removeItem('fr7pid');location.reload()}
$('create').onclick=async()=>{try{const r=await api('create',{name:$('name').value.trim()||'Host'});room=r.room;myId=r.playerId;localStorage.fr7room=room;localStorage.fr7pid=myId;enter();render(r.state);tone(520,.09)}catch(e){err.textContent=e.message}}
$('join').onclick=async()=>{try{const r=await api('join',{name:$('name').value.trim()||'Player',room:$('roomCode').value});room=r.room;myId=r.playerId;localStorage.fr7room=room;localStorage.fr7pid=myId;enter();render(r.state);tone(520,.09)}catch(e){err.textContent=e.message}}
$('roomCode').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''));
for(const [id,path] of [['hit','hit'],['stay','stay'],['start','start'],['next','next']])$(id).onclick=()=>{haptic();tone(id==='stay'?310:560,.07,id==='hit'?'square':'sine');api(path).catch(e=>toast(e.message))};
$('leave').onclick=()=>showModal(`<h2>Leave the table?</h2><p>You can return while the room is still active using the same device.</p><button class="menu-action" id="confirmLeave">LEAVE ROOM</button>`,'leave');
$('copyCode').onclick=shareRoom;$('share').onclick=shareRoom;
async function shareRoom(){const text=`Join my Flip Rush 7 room: ${state.code}`;try{if(navigator.share)await navigator.share({title:'Flip Rush 7',text});else{await navigator.clipboard.writeText(state.code);toast('Room code copied')}}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1700)}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function actionName(n){return n==='freeze'?'FREEZE':n==='flip3'?'FLIP THREE':'SECOND CHANCE'}
function calculatePreview(p){if(!p||p.busted)return 0;let n=p.cards.reduce((s,c)=>s+c.value,0);if(p.mods.some(c=>c.type==='multiplier'))n*=2;n+=p.mods.filter(c=>c.type==='modifier').reduce((s,c)=>s+c.value,0);if(p.cards.length>=7)n+=15;return n}
function cardEl(card,index=0){const e=document.createElement('div');e.className='card';e.style.animationDelay=`${Math.min(index*25,160)}ms`;if(card.type==='number'){e.textContent=card.value;e.dataset.label=card.value;e.classList.add('number',`n${card.value}`)}else if(card.type==='modifier'){e.textContent='+'+card.value;e.classList.add('mod');e.dataset.label='BONUS'}else if(card.type==='multiplier'){e.textContent='×2';e.classList.add('mult');e.dataset.label='BOOST'}else{e.textContent=actionName(card.name);e.classList.add('action',card.name);e.dataset.label='ACTION'}return e}
function renderTargetPicker(s){const p=$('targetPicker'),a=s.pendingAction;if(!a||a.chooserId!==myId){p.classList.add('hidden');p.innerHTML='';return}const eligible=s.players.filter(x=>a.eligibleIds.includes(x.id));p.classList.remove('hidden');p.innerHTML=`<div class="target-title">Choose who receives <b>${actionName(a.card.name)}</b></div><div class="target-list"></div>`;const list=p.querySelector('.target-list');eligible.forEach(x=>{const b=document.createElement('button');b.className='target';b.innerHTML=`<span>${esc(x.name)}</span><small>${x.id===myId?'YOU':`${x.cards.length} NUMBER CARDS`}</small>`;b.onclick=()=>{haptic();api('target',{targetId:x.id}).catch(e=>toast(e.message))};list.appendChild(b)})}
function confetti(){const root=$('confetti'),colors=['#32e5cb','#ffdd42','#ff4f8b','#8e7dff','#fff'];root.innerHTML='';for(let i=0;i<70;i++){const x=document.createElement('i');x.className='confetti-piece';x.style.left=Math.random()*100+'%';x.style.background=colors[i%colors.length];x.style.animationDelay=Math.random()*.8+'s';x.style.animationDuration=1.8+Math.random()*1.4+'s';root.appendChild(x)}setTimeout(()=>root.innerHTML='',3500)}
function latestReactionFor(s,playerId){const reactions=s.reactions||[];for(let i=reactions.length-1;i>=0;i--)if(reactions[i].playerId===playerId)return reactions[i];return null}
function showReaction(reaction,s){if(!reaction||seenReactions.has(reaction.id))return;seenReactions.add(reaction.id);if(seenReactions.size>80){const first=seenReactions.values().next().value;seenReactions.delete(first)}const sender=s.players.find(p=>p.id===reaction.playerId);const pop=$('reactionPop');if(!pop)return;pop.innerHTML=`<span>${esc(reaction.emoji)}</span><div><b>${esc(sender?.name||'Player')}</b><small>SENT A REACTION</small></div>`;pop.classList.remove('show');void pop.offsetWidth;pop.classList.add('show');clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>pop.classList.remove('show'),2600);if(reaction.playerId!==myId){tone(490,.07,'triangle');haptic(10)}}
function renderNewReactions(s){const reactions=s.reactions||[];if(!reactions.length)return;for(const reaction of reactions)showReaction(reaction,s)}
function showPhrase(message,s){if(!message||seenPhrases.has(message.id))return;seenPhrases.add(message.id);if(seenPhrases.size>80){const first=seenPhrases.values().next().value;seenPhrases.delete(first)}const sender=s.players.find(p=>p.id===message.playerId);const pop=$('phrasePop');if(!pop)return;pop.innerHTML=`<b>${esc(sender?.name||'Player')} SAYS</b><strong>${esc(message.phrase)}</strong>`;pop.classList.remove('show');void pop.offsetWidth;pop.classList.add('show');clearTimeout(phraseTimer);phraseTimer=setTimeout(()=>pop.classList.remove('show'),3000);if(message.playerId!==myId){tone(610,.09,'triangle');setTimeout(()=>tone(760,.08,'triangle'),90);haptic(14)}}
function renderNewPhrases(s){for(const message of (s.phrases||[]))showPhrase(message,s)}
function openPhraseTray(){const tray=$('phraseTray'),me=state?.players?.find(p=>p.id===myId);const phrases=[...QUICK_PHRASES];if((me?.name||'').trim().toLowerCase()==='becca')phrases.push(BECCA_PHRASE);tray.innerHTML=phrases.map(phrase=>`<button data-phrase="${esc(phrase)}" class="${phrase===BECCA_PHRASE?'becca-phrase':''}">${esc(phrase)}</button>`).join('');$('reactionTray').classList.add('hidden');tray.classList.toggle('hidden')}

function statusText(s,myTurn){if(s.pendingAction){const c=s.players.find(p=>p.id===s.pendingAction.chooserId);return[c?.id===myId?`CHOOSE A TARGET FOR ${actionName(s.pendingAction.card.name)}`:`${c?.name} IS CHOOSING A TARGET`,'Action card in play']}if(s.phase==='lobby')return[`WAITING FOR PLAYERS (${s.players.length}/9)`,'Share the room code to invite friends'];if(s.phase==='playing')return[myTurn?'YOUR DECISION — FLIP OR STAY':`${s.players[s.turnIndex]?.name}'S TURN`,myTurn?'How far will you push it?':'Watch the table'];if(s.phase==='roundEnd')return['ROUND COMPLETE','Scores have been banked'];return[`${s.winner} WINS!`,'Game complete']}
function render(s){const previous=state;state=s;$('copyCode').querySelector('b').textContent=s.code;$('round').textContent=s.round;$('deckCount').textContent=s.deckCount;const me=s.players.find(p=>p.id===myId),turn=s.players[s.turnIndex],myTurn=s.phase==='playing'&&!s.pendingAction&&turn?.id===myId;
$('players').innerHTML='';s.players.forEach((p,i)=>{const e=document.createElement('div');e.className='player '+(s.phase==='playing'&&!s.pendingAction&&i===s.turnIndex?'turn':'');e.dataset.playerId=p.id;const live=p.busted?'BUSTED':p.frozen?`FROZEN ${p.roundScore}`:p.stayed?`BANKED ${p.roundScore}`:`${p.cards.length} NUMBERS`;const reaction=latestReactionFor(s,p.id);e.innerHTML=`<span class="dot ${p.connected?'':'off'}"></span>${reaction?`<div class="player-reaction">${esc(reaction.emoji)}</div>`:''}<div class="avatar" style="background:${avatarColors[i%avatarColors.length]}">${esc(p.name.charAt(0).toUpperCase())}</div><div class="name">${esc(p.name)}${p.id===s.hostId?' ★':''}${i===s.dealerIndex?' ◇':''}</div><div class="score">${p.score}</div><small>${live}${p.second?' · 2ND CHANCE':''}</small>`;$('players').appendChild(e)});
const area=$('myArea');area.innerHTML='';if(me)[...me.cards,...me.mods,...(me.second?[{type:'action',name:'second'}]:[])].forEach((c,i)=>area.appendChild(cardEl(c,i)));$('scorePreview').querySelector('b').textContent=calculatePreview(me);
renderTargetPicker(s);$('hit').disabled=!myTurn;$('stay').disabled=!myTurn||!(me&&(me.cards.length||me.mods.length||me.second));$('hit').classList.toggle('hidden',s.phase!=='playing'||!!s.pendingAction);$('stay').classList.toggle('hidden',s.phase!=='playing'||!!s.pendingAction);$('start').classList.toggle('hidden',!(s.phase==='lobby'&&s.hostId===myId));$('next').classList.toggle('hidden',!(s.phase==='roundEnd'&&s.hostId===myId));$('lobbyCard').classList.toggle('hidden',s.phase!=='lobby');$('table').classList.toggle('hidden',s.phase==='lobby');
const [big,small]=statusText(s,myTurn);$('status').innerHTML=`<span class="pulse"></span><b>${esc(big)}</b><small>${esc(small)}</small>`;$('log').innerHTML=s.log.map(x=>`<div>${esc(x)}</div>`).join('');
renderNewReactions(s);renderNewPhrases(s);
if(previous){const oldMe=previous.players.find(p=>p.id===myId);const newCount=(me?.cards.length||0)+(me?.mods.length||0)+(me?.second?1:0),oldCount=(oldMe?.cards.length||0)+(oldMe?.mods.length||0)+(oldMe?.second?1:0);if(newCount>oldCount){tone(680,.08,'triangle');haptic(12)}if(previous.phase!=='gameOver'&&s.phase==='gameOver'){confetti();tone(740,.3);setTimeout(()=>tone(980,.35),180)}}lastPhase=s.phase}
function showModal(html,mode=''){$('modalBody').innerHTML=html;$('modal').classList.remove('hidden');if(mode==='leave')setTimeout(()=>{const b=$('confirmLeave');if(b)b.onclick=leave},0)}
function closeModal(){$('modal').classList.add('hidden')}
$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()}
const help=`<h2>How to play</h2><p>Build the highest score without revealing a duplicate number.</p><ol><li>On your turn, choose <b>Flip</b> to draw or <b>Stay</b> to bank your round value.</li><li>A duplicate number busts your round unless a Second Chance protects you. You may hold only one Second Chance; if you draw another, give it to another active player who does not have one, or discard it if nobody can receive it.</li><li>Second Chance protects only against a duplicate Number card. It does not block Freeze.</li><li>Freeze and Flip Three may target any active player, including yourself.</li><li>During Flip Three, all three revealed cards count unless the target busts or reaches Flip 7. A Second Chance resolves immediately; other Action cards wait until the three-card sequence finishes.</li><li>Seven unique Number cards immediately end the round and award a 15-point bonus. ×2 doubles only the Number-card subtotal; additive modifiers and the +15 bonus are added afterward.</li><li>Once the high score is at least 200, the highest total wins. If the highest score is tied, everyone plays another full round.</li></ol><button class="menu-action" onclick="document.getElementById('modal').classList.add('hidden')">GOT IT</button>`;
$('howBtn').onclick=()=>showModal(help);$('menuBtn').onclick=()=>showModal(`<h2>Game menu</h2><button class="menu-action" id="menuHow">HOW TO PLAY</button><button class="menu-action" id="menuSound">${soundOn?'MUTE SOUND':'TURN SOUND ON'}</button><button class="menu-action" id="menuLeave">LEAVE ROOM</button>`);$('modalBody').addEventListener('click',e=>{if(e.target.id==='menuHow')showModal(help);if(e.target.id==='menuSound'){soundOn=!soundOn;localStorage.fr7sound=soundOn?'on':'off';toast(soundOn?'Sound on':'Sound muted');closeModal()}if(e.target.id==='menuLeave')leave()});
$('soundBtn').onclick=()=>{soundOn=!soundOn;localStorage.fr7sound=soundOn?'on':'off';$('soundBtn').textContent=soundOn?'♪':'×';if(soundOn)tone(520,.08)};$('soundBtn').textContent=soundOn?'♪':'×';
$('react').onclick=()=>{haptic(8);$('phraseTray').classList.add('hidden');$('reactionTray').classList.toggle('hidden')};$('reactionTray').onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.id==='phraseMenuBtn'){haptic(8);openPhraseTray();return}const emoji=button.dataset.emoji;if(!emoji)return;$('reactionTray').classList.add('hidden');haptic(8);api('react',{emoji}).then(()=>{toast(`${emoji} sent to everyone`);tone(420,.05)}).catch(err=>toast(err.message))};$('phraseTray').onclick=e=>{const button=e.target.closest('button[data-phrase]');if(!button)return;const phrase=button.dataset.phrase;$('phraseTray').classList.add('hidden');haptic(8);api('phrase',{phrase}).then(()=>{toast('Phrase sent to everyone');tone(520,.06)}).catch(err=>toast(err.message))};
if(room&&myId){enter();api('state').catch(()=>{localStorage.removeItem('fr7room');localStorage.removeItem('fr7pid');location.reload()})}
setInterval(()=>{if(room&&myId)api('state').catch(()=>{})},800);if('serviceWorker'in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()));if(window.caches)caches.keys().then(keys=>keys.forEach(k=>caches.delete(k)))}
