let state=null,myId=localStorage.fr7pid||'',room=localStorage.fr7room||'',lastCardCount=0,lastPhase='',soundOn=localStorage.fr7sound!=='off',pollFailures=0,reactionTimer=null,phraseTimer=null,lastOpponentTableSig='';
let flipThreeTransferId='',flipThreeTransferStage='';
let actionTransferId='',actionTransferStage='',actionTransferOutcome='',actionTransferTargetId='';
let voiceOn=false,voiceSpeaking=false,localVoiceStream=null,voiceContext=null,voiceAnalyser=null,voiceMonitorFrame=0,voiceSignalTimer=null,lastVoiceActivity=0;
const voicePeers=new Map();
const seenReactions=new Set(),seenPhrases=new Set();
const ACTION_REVEAL_MS=1000,SECOND_CHANCE_REVEAL_MS=1000,secondChanceVisuals=new Map();
let pendingActionRevealKey='',pendingActionRevealStarted=0,pendingActionRevealTimer=null;
let screenEffectTimer=null;
const QUICK_PHRASES=['Nice Job!',"You're almost there!",'So Close!','You suck!','Oh Man!'];
const BECCA_PHRASE="You're a peckerhead!";
const newDeviceId=()=>globalThis.crypto?.randomUUID?.()||`device-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const deviceId=localStorage.fr7device||newDeviceId();
localStorage.fr7device=deviceId;
const invitedRoom=(new URLSearchParams(location.search).get('room')||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);
const $=id=>document.getElementById(id),home=$('home'),game=$('game'),err=$('error');
const avatarColors=['#32e5cb','#ffdd42','#ff6f91','#8e7dff','#ff914d','#72d7ff'];
$('name').value=localStorage.fr7name||'';
if(invitedRoom){$('roomCode').value=invitedRoom;if(room&&room!==invitedRoom){room='';myId='';localStorage.removeItem('fr7room');localStorage.removeItem('fr7pid')}}
function haptic(ms=18){if(navigator.vibrate)navigator.vibrate(ms)}
function tone(freq=440,duration=.08,type='sine',gain=.05){if(!soundOn)return;try{const C=window.AudioContext||window.webkitAudioContext,a=new C(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.stop(a.currentTime+duration)}catch{}}
function showLocalScreenEffect(type){
 clearTimeout(screenEffectTimer);$('screenEffect')?.remove();
 const effect=document.createElement('div');effect.id='screenEffect';effect.className=`screen-effect ${type==='freeze'?'freeze-screen-effect':'shatter-screen-effect'}`;effect.setAttribute('aria-hidden','true');
 if(type==='freeze')effect.innerHTML='<i class="ice-edge top"></i><i class="ice-edge right"></i><i class="ice-edge bottom"></i><i class="ice-edge left"></i>';
 else effect.innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><g><polygon points="52,47 69,17 61,48 86,35 55,51 79,73 53,54 62,94 49,55 33,86 46,53 8,66 44,49 18,23 48,46"/><polygon points="52,47 69,17 61,48"/><polygon points="55,51 86,35 79,73"/><polygon points="49,55 62,94 33,86"/><polygon points="44,49 8,66 18,23"/><path pathLength="100" d="M52 47L69 17 73 2M52 47L61 48 86 35 97 29M55 51L79 73 96 82M53 54L62 94 64 100M49 55L33 86 24 100M46 53L8 66 0 72M44 49L18 23 3 13M48 46L39 17 34 0"/><path pathLength="100" d="M52 47L57 34 52 24 58 11M61 48L71 42 75 48 91 44M55 51L67 58 64 67 82 83M53 54L54 70 48 78 52 99M49 55L40 67 41 76 29 91M46 53L31 57 24 52 4 59M44 49L33 39 35 31 15 17M48 46L47 33 40 27 42 6"/><path pathLength="100" d="M52 47L45 43 38 45 28 38M52 47L58 52 69 51 78 58M52 47L50 39 54 31M52 47L47 57 49 68 43 76"/></g></svg>`;
 document.body.appendChild(effect);screenEffectTimer=setTimeout(()=>{effect.remove();if($('screenEffect')===effect)screenEffectTimer=null},2000);
}
function voiceSupported(){return Boolean(navigator.mediaDevices?.getUserMedia&&window.RTCPeerConnection)}
function updateMicButton(){const b=$('micBtn');if(!b)return;b.classList.toggle('voice-on',voiceOn);b.classList.toggle('voice-speaking',voiceOn&&voiceSpeaking);b.setAttribute('aria-label',voiceOn?'Mute microphone':'Turn microphone on');b.title=voiceOn?(voiceSpeaking?'Microphone on — you are speaking':'Microphone on — tap to mute'):'Microphone off';if(!voiceSupported()){b.disabled=true;b.title='Voice chat is not supported on this device'}}
async function voicePost(path,data={}){const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room,playerId:myId,...data}),cache:'no-store'});const json=await response.json();if(!json.ok)throw new Error(json.error||'Voice chat error');return json}
function voiceStatus(enabled,speaking=false){if(!room||!myId)return Promise.resolve();return voicePost('voice-status',{enabled:Boolean(enabled),speaking:Boolean(enabled&&speaking)}).catch(()=>{})}
function closeVoicePeer(peerId){const entry=voicePeers.get(peerId);if(!entry)return;voicePeers.delete(peerId);entry.closing=true;try{entry.pc.onconnectionstatechange=null;entry.pc.onicecandidate=null;entry.pc.ontrack=null;entry.pc.close()}catch{}try{entry.audio.pause();entry.audio.srcObject=null;entry.audio.remove()}catch{}}
function closeAllVoicePeers(){for(const peerId of [...voicePeers.keys()])closeVoicePeer(peerId)}
async function sendVoiceSignal(targetId,signal){try{await voicePost('voice-signal',{targetId,signal})}catch(e){if(voiceOn&&String(e.message||'').includes('enable voice'))return}}
function serialDescription(description){return description?.toJSON?description.toJSON():description}
function serialCandidate(candidate){return candidate?.toJSON?candidate.toJSON():candidate}
function makeVoicePeer(peerId){if(voicePeers.has(peerId))return voicePeers.get(peerId);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});const audio=document.createElement('audio');audio.autoplay=true;audio.playsInline=true;audio.dataset.voicePeer=peerId;$('voiceAudioRack')?.appendChild(audio);const entry={pc,audio,pendingCandidates:[],offerStarted:false,closing:false};voicePeers.set(peerId,entry);for(const track of (localVoiceStream?.getTracks()||[]))pc.addTrack(track,localVoiceStream);pc.onicecandidate=event=>{if(event.candidate&&voiceOn)sendVoiceSignal(peerId,{type:'candidate',candidate:serialCandidate(event.candidate)})};pc.ontrack=event=>{const stream=event.streams?.[0]||new MediaStream([event.track]);audio.srcObject=stream;audio.play().catch(()=>{})};pc.onconnectionstatechange=()=>{if(entry.closing)return;if(pc.connectionState==='failed'||pc.connectionState==='closed'){closeVoicePeer(peerId);setTimeout(()=>{const remote=state?.players?.find(p=>p.id===peerId);if(voiceOn&&remote?.voiceEnabled&&remote?.connected)ensureVoicePeer(peerId)},900)}};return entry}
async function startVoiceOffer(peerId,entry){if(!voiceOn||entry.offerStarted||entry.pc.signalingState!=='stable')return;entry.offerStarted=true;try{const offer=await entry.pc.createOffer({offerToReceiveAudio:true});await entry.pc.setLocalDescription(offer);await sendVoiceSignal(peerId,{type:'offer',description:serialDescription(entry.pc.localDescription)})}catch{entry.offerStarted=false}}
function ensureVoicePeer(peerId){if(!voiceOn||peerId===myId)return null;const entry=makeVoicePeer(peerId);if(myId<peerId)startVoiceOffer(peerId,entry);return entry}
async function flushVoiceCandidates(entry){if(!entry.pc.remoteDescription)return;while(entry.pendingCandidates.length){const candidate=entry.pendingCandidates.shift();try{await entry.pc.addIceCandidate(candidate)}catch{}}}
async function handleVoiceSignal(message){if(!voiceOn||!message?.fromId||!message.signal)return;const peerId=message.fromId,signal=message.signal,entry=ensureVoicePeer(peerId);if(!entry)return;const pc=entry.pc;try{if(signal.type==='offer'){await pc.setRemoteDescription(signal.description);await flushVoiceCandidates(entry);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await sendVoiceSignal(peerId,{type:'answer',description:serialDescription(pc.localDescription)})}else if(signal.type==='answer'){if(pc.signalingState==='have-local-offer'){await pc.setRemoteDescription(signal.description);await flushVoiceCandidates(entry)}}else if(signal.type==='candidate'&&signal.candidate){if(pc.remoteDescription)await pc.addIceCandidate(signal.candidate);else entry.pendingCandidates.push(signal.candidate)}}catch{}}
async function pollVoiceSignals(){if(!voiceOn||!room||!myId)return;try{const q=new URLSearchParams({room,playerId:myId});const response=await fetch('/api/voice-signals?'+q.toString(),{cache:'no-store'});const json=await response.json();if(json.ok)for(const message of (json.signals||[]))await handleVoiceSignal(message)}catch{}}
function startVoiceSignalPolling(){clearInterval(voiceSignalTimer);pollVoiceSignals();voiceSignalTimer=setInterval(pollVoiceSignals,320)}
function stopVoiceMonitor(){if(voiceMonitorFrame)cancelAnimationFrame(voiceMonitorFrame);voiceMonitorFrame=0;if(voiceContext){voiceContext.close().catch(()=>{});voiceContext=null}voiceAnalyser=null;voiceSpeaking=false;updateMicButton()}
function startVoiceMonitor(stream){stopVoiceMonitor();try{const C=window.AudioContext||window.webkitAudioContext;voiceContext=new C();voiceContext.resume?.().catch(()=>{});const source=voiceContext.createMediaStreamSource(stream);voiceAnalyser=voiceContext.createAnalyser();voiceAnalyser.fftSize=512;source.connect(voiceAnalyser);const data=new Uint8Array(voiceAnalyser.fftSize);lastVoiceActivity=0;const frame=()=>{if(!voiceOn||!voiceAnalyser)return;voiceAnalyser.getByteTimeDomainData(data);let sum=0;for(const v of data){const n=(v-128)/128;sum+=n*n}const rms=Math.sqrt(sum/data.length),now=Date.now();if(rms>.035)lastVoiceActivity=now;const talking=lastVoiceActivity>0&&now-lastVoiceActivity<280;if(talking!==voiceSpeaking){voiceSpeaking=talking;updateMicButton();voiceStatus(true,voiceSpeaking)}voiceMonitorFrame=requestAnimationFrame(frame)};voiceMonitorFrame=requestAnimationFrame(frame)}catch{}}
function syncVoicePeers(s){if(!voiceOn)return;const wanted=new Set((s.players||[]).filter(p=>p.id!==myId&&p.connected&&p.voiceEnabled).map(p=>p.id));for(const peerId of wanted)ensureVoicePeer(peerId);for(const peerId of [...voicePeers.keys()])if(!wanted.has(peerId))closeVoicePeer(peerId)}
async function enableVoice(){if(voiceOn)return;if(!voiceSupported()){toast('Voice chat is not supported on this device');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});localVoiceStream=stream;voiceOn=true;voiceSpeaking=false;updateMicButton();startVoiceMonitor(stream);await voiceStatus(true,false);startVoiceSignalPolling();try{const result=await api('state');syncVoicePeers(result.state)}catch{}toast('Microphone on — voice chat ready');haptic(12)}catch(e){voiceOn=false;updateMicButton();const denied=e?.name==='NotAllowedError'||e?.name==='SecurityError';toast(denied?'Microphone permission was not allowed':'Could not start microphone')}}
function disableVoice(notify=true){if(!voiceOn&&!localVoiceStream)return;voiceOn=false;voiceSpeaking=false;clearInterval(voiceSignalTimer);voiceSignalTimer=null;stopVoiceMonitor();closeAllVoicePeers();for(const track of (localVoiceStream?.getTracks()||[]))try{track.stop()}catch{}localVoiceStream=null;voiceStatus(false,false);updateMicButton();if(notify){toast('Microphone muted');haptic(8)}}
function toggleVoice(){if(voiceOn)disableVoice();else enableVoice()}
function voicePageHide(){if(voiceOn&&room&&myId){try{const blob=new Blob([JSON.stringify({room,playerId:myId,enabled:false,speaking:false})],{type:'application/json'});navigator.sendBeacon('/api/voice-status',blob)}catch{}}for(const track of (localVoiceStream?.getTracks()||[]))try{track.stop()}catch{}}
async function api(path,data={}){try{const isState=path==='state';let url='/api/'+path;const options={method:isState?'GET':'POST',headers:{'Content-Type':'application/json'}};if(isState){const params=new URLSearchParams({room,playerId:myId});url+='?'+params.toString()}else{const payload={...data};if(path!=='create'&&path!=='join'){payload.room=room;payload.playerId=myId}options.body=JSON.stringify(payload)}const response=await fetch(url,options);const json=await response.json();if(!json.ok)throw new Error(json.error);pollFailures=0;$('connection').classList.add('hidden');if(json.state)render(json.state);return json}catch(e){pollFailures++;if(pollFailures>2&&room)$('connection').classList.remove('hidden');throw e}}
function enter(){home.classList.remove('active');game.classList.add('active')}
function leave(){disableVoice(false);localStorage.removeItem('fr7room');localStorage.removeItem('fr7pid');location.reload()}
$('create').onclick=async()=>{try{const name=$('name').value.trim()||'Host',r=await api('create',{name,deviceId});room=r.room;myId=r.playerId;localStorage.fr7room=room;localStorage.fr7pid=myId;localStorage.fr7name=name;enter();render(r.state);ensurePushRegistration(false);tone(520,.09)}catch(e){err.textContent=e.message}}
$('join').onclick=async()=>{try{const name=$('name').value.trim()||'Player',r=await api('join',{name,room:$('roomCode').value,deviceId});room=r.room;myId=r.playerId;localStorage.fr7room=room;localStorage.fr7pid=myId;localStorage.fr7name=name;enter();render(r.state);ensurePushRegistration(false);tone(520,.09)}catch(e){err.textContent=e.message}}
$('roomCode').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''));
for(const [id,path] of [['hit','hit'],['stay','stay'],['start','start'],['next','next']])$(id).onclick=()=>{haptic();tone(id==='stay'?310:560,.07,id==='hit'?'square':'sine');api(path).catch(e=>toast(e.message))};
$('leave').onclick=()=>showModal(`<h2>Leave the table?</h2><p>You can return while the room is still active using the same device.</p><button class="menu-action" id="confirmLeave">LEAVE ROOM</button>`,'leave');
$('copyCode').onclick=shareRoom;$('share').onclick=shareRoom;$('notifyPast').onclick=openInvitePlayers;
function roomInviteUrl(){const code=state?.code||room,url=new URL('online.html',location.href);url.searchParams.set('room',code);url.searchParams.set('invite','1');const theme=new URLSearchParams(location.search).get('theme');if(theme)url.searchParams.set('theme',theme);return url.href}
async function shareRoom(){const code=state?.code||room,sender=state?.players?.find(p=>p.id===myId)?.name||localStorage.fr7name||'A friend',text=`${sender} invited you to play Flip Rush 7. Join room ${code}.`,url=roomInviteUrl();try{if(navigator.share)await navigator.share({title:'Flip Rush 7 invitation',text,url});else{await navigator.clipboard.writeText(`${text}\n${url}`);toast('Invitation link copied')}}catch(error){if(error?.name!=='AbortError')try{await navigator.clipboard.writeText(`${text}\n${url}`);toast('Invitation link copied')}catch{toast('Could not share the invitation')}}}
function pushSupported(){return 'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window}
function base64Key(value){const padding='='.repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function ensurePushRegistration(requestPermission){if(!pushSupported()){if(requestPermission)toast('Push notifications are not supported on this device');return false}let permission=Notification.permission;if(permission==='default'&&requestPermission)permission=await Notification.requestPermission();if(permission!=='granted'){if(requestPermission)toast(permission==='denied'?'Allow notifications in your browser settings':'Notifications were not enabled');return false}try{const keyResult=await fetch('/api/push/public-key',{cache:'no-store'}).then(r=>r.json());if(!keyResult.ok||!keyResult.publicKey)throw new Error('Notification service unavailable');const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription(),savedKey=localStorage.fr7pushkey||'';if(subscription&&savedKey&&savedKey!==keyResult.publicKey){await subscription.unsubscribe();subscription=null}if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64Key(keyResult.publicKey)});const response=await fetch('/api/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId,name:$('name').value.trim()||localStorage.fr7name||'Player',subscription:subscription.toJSON()})}).then(r=>r.json());if(!response.ok)throw new Error(response.error||'Notification registration failed');localStorage.fr7pushkey=keyResult.publicKey;if(requestPermission)toast('Game invitations are enabled');return true}catch(error){if(requestPermission)toast(error.message||'Could not enable notifications');return false}}
function pastPlayers(){try{const value=JSON.parse(localStorage.fr7pastplayers||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
function rememberPastPlayers(s){const saved=pastPlayers(),byId=new Map(saved.map(item=>[item.inviteId,item]));for(const player of (s.players||[])){if(player.computer||!player.inviteId||player.inviteId===deviceId)continue;byId.set(player.inviteId,{inviteId:player.inviteId,name:player.name,lastPlayed:Date.now()})}const next=[...byId.values()].sort((a,b)=>b.lastPlayed-a.lastPlayed).slice(0,24);localStorage.fr7pastplayers=JSON.stringify(next)}
function openInvitePlayers(){const currentIds=new Set((state?.players||[]).map(p=>p.inviteId).filter(Boolean)),recent=pastPlayers().filter(item=>item.inviteId&&!currentIds.has(item.inviteId)),supported=pushSupported(),permission=supported?Notification.permission:'unsupported';let notice=permission==='granted'?'<div class="invite-note">This phone can also receive invitations from people you have played with.</div>':permission==='denied'?'<div class="invite-note">Notifications are blocked on this phone. You can allow them in your browser or app settings.</div>':supported?'<button id="enableInvites" class="menu-action">ENABLE INVITATIONS ON THIS PHONE</button>':'<div class="invite-note">Push notifications are not supported here. Text and share invitations still work.</div>';const list=recent.length?`<div class="past-player-list">${recent.map(item=>`<div class="past-player"><span>${esc(item.name)}</span><button data-invite-id="${esc(item.inviteId)}">INVITE</button></div>`).join('')}</div>`:'<div class="invite-note">People you play with will appear here for future invitations.</div>';showModal(`<h2>Invite past players</h2><p>Send a phone notification to someone you have played with before.</p>${list}${notice}`);setTimeout(()=>{const enable=$('enableInvites');if(enable)enable.onclick=async()=>{enable.disabled=true;const ok=await ensurePushRegistration(true);if(ok)openInvitePlayers();else enable.disabled=false};$('modalBody').querySelectorAll('[data-invite-id]').forEach(button=>button.onclick=async()=>{button.disabled=true;button.textContent='SENDING…';try{await api('push/invite',{targetDeviceId:button.dataset.inviteId});button.textContent='SENT';toast('Invitation sent')}catch(error){button.disabled=false;button.textContent='INVITE';toast(error.message)}})},0)}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1700)}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function actionName(n){return n==='freeze'?'FREEZE':n==='flip3'?'FLIP THREE':'SECOND CHANCE'}
function calculatePreview(p){if(!p||p.busted)return 0;let n=p.cards.reduce((s,c)=>s+c.value,0);if(p.mods.some(c=>c.type==='multiplier'))n*=2;n+=p.mods.filter(c=>c.type==='modifier').reduce((s,c)=>s+c.value,0);if(p.cards.length>=7)n+=15;return n}
function cardEl(card,index=0,animate=true){const e=document.createElement('div');e.className='card';e.style.animationDelay=`${Math.min(index*25,160)}ms`;if(!animate)e.style.animation='none';if(card.type==='number'){e.textContent=card.value;e.dataset.label=card.value;e.classList.add('number',`n${card.value}`)}else if(card.type==='modifier'){e.textContent='+'+card.value;e.classList.add('mod');e.dataset.label='BONUS'}else if(card.type==='multiplier'){e.textContent='×2';e.classList.add('mult');e.dataset.label='BOOST'}else{e.textContent=actionName(card.name);e.classList.add('action',card.name);e.dataset.label='ACTION'}return e}
function renderDiscardPile(s){const root=$('discardVisual');if(!root)return;$('discardCount').textContent=s.discardCount||0;root.innerHTML='';if(s.discardTop)root.appendChild(cardEl(s.discardTop,0,false));else root.innerHTML='<div class="discard-empty">DISCARD</div>'}
function flipThreeAnchor(playerId){if(playerId===myId)return $('myArea');const table=$('botTable');if(table)for(const seat of table.children)if(seat.dataset.playerId===playerId)return seat;const strip=$('players');if(strip)for(const player of strip.children)if(player.dataset.playerId===playerId)return player;return $('table')}
function placeFlipThreeCard(card,anchor){if(!card||!anchor)return;const rect=anchor.getBoundingClientRect(),width=card.offsetWidth||68,height=card.offsetHeight||98;card.style.left=`${Math.max(4,Math.min(innerWidth-width-4,rect.left+(rect.width-width)/2))}px`;card.style.top=`${Math.max(4,Math.min(innerHeight-height-4,rect.top+(rect.height-height)/2))}px`}
function syncFlipThreeTransfer(s){const visual=s.flipThreeVisual;let card=$('flipThreeTransferCard');if(!visual){if(card&&!card.classList.contains('discarding')){flipThreeTransferId='';flipThreeTransferStage='';card.classList.add('discarding');placeFlipThreeCard(card,$('discardVisual'));setTimeout(()=>card.remove(),520)}return}const stage=visual.stage||'giver',anchorId=stage==='giver'?visual.fromId:visual.targetId;if(!card||flipThreeTransferId!==visual.id){card?.remove();card=cardEl({type:'action',name:'flip3'},0,false);card.id='flipThreeTransferCard';card.classList.add('flip-three-transfer-card');document.body.appendChild(card);flipThreeTransferId=visual.id;flipThreeTransferStage=stage;placeFlipThreeCard(card,flipThreeAnchor(anchorId));tone(590,.1,'triangle');return}if(stage!==flipThreeTransferStage){flipThreeTransferStage=stage;card.classList.add('moving');requestAnimationFrame(()=>placeFlipThreeCard(card,flipThreeAnchor(anchorId)));setTimeout(()=>card.classList.remove('moving'),680);if(visual.targetId===myId){haptic(24);tone(760,.16,'triangle')}}else placeFlipThreeCard(card,flipThreeAnchor(anchorId))}
function syncActionCardTransfer(s){const visual=s.actionCardVisual;let card=$('actionTransferCard');if(!visual){if(card&&!card.classList.contains('discarding')&&!card.classList.contains('settling')){const outcome=actionTransferOutcome,targetId=actionTransferTargetId;actionTransferId='';actionTransferStage='';actionTransferOutcome='';actionTransferTargetId='';if(outcome==='discard'){card.classList.add('discarding');placeFlipThreeCard(card,$('discardVisual'));setTimeout(()=>card.remove(),520)}else{card.classList.add('settling');placeFlipThreeCard(card,flipThreeAnchor(targetId));setTimeout(()=>card.remove(),420)}}return}const stage=visual.stage||'giver',anchorId=stage==='giver'?visual.fromId:visual.targetId;if(!card||actionTransferId!==visual.id){card?.remove();card=cardEl({type:'action',name:visual.name},0,false);card.id='actionTransferCard';card.classList.add('action-transfer-card');document.body.appendChild(card);actionTransferId=visual.id;actionTransferStage=stage;actionTransferOutcome=visual.outcome||'settle';actionTransferTargetId=visual.targetId;placeFlipThreeCard(card,flipThreeAnchor(anchorId));tone(visual.name==='freeze'?520:680,.1,'triangle');return}actionTransferOutcome=visual.outcome||'settle';actionTransferTargetId=visual.targetId;if(stage!==actionTransferStage){actionTransferStage=stage;card.classList.add('moving');requestAnimationFrame(()=>placeFlipThreeCard(card,flipThreeAnchor(anchorId)));setTimeout(()=>card.classList.remove('moving'),680);if(visual.targetId===myId){haptic(24);tone(visual.name==='freeze'?460:780,.16,'triangle')}}else placeFlipThreeCard(card,flipThreeAnchor(anchorId))}
function cardSortRank(c){if(c.type==='number')return c.value;if(c.type==='modifier')return 100+c.value;if(c.type==='multiplier')return 200;if(c.type==='action'&&c.name==='second')return 300;return 400}
function pendingActionCardFor(p,s=state){const a=s?.pendingAction;return a&&p&&a.chooserId===p.id?a.card:null}
function visibleCards(p,s=state){if(!p)return[];const visual=secondChanceVisuals.get(p.id),protecting=visual&&Date.now()<visual.until;const cards=[...p.cards];if(protecting)cards.push({type:'number',value:visual.value});const out=[...cards,...p.mods,...(p.statusCards||[]),...((p.second||protecting)?[{type:'action',name:'second'}]:[])],pending=pendingActionCardFor(p,s);if(pending)out.push(pending);return out.sort((a,b)=>cardSortRank(a)-cardSortRank(b))}
function cardKey(c){return `${c.type}:${c.name||''}:${c.value??''}`}
function handSignature(p,s=state){return visibleCards(p,s).map(cardKey).join('|')}
function actionRevealKey(s){const a=s?.pendingAction;if(!a)return'';return `${a.chooserId}|${a.card?.name||''}|${(a.eligibleIds||[]).join(',')}|${s.log?.length||0}`}
function actionRevealActive(s){return Boolean(s?.pendingAction&&actionRevealKey(s)===pendingActionRevealKey&&Date.now()-pendingActionRevealStarted<ACTION_REVEAL_MS)}
function updateActionReveal(s){const key=actionRevealKey(s);if(!key){pendingActionRevealKey='';pendingActionRevealStarted=0;clearTimeout(pendingActionRevealTimer);pendingActionRevealTimer=null;return}if(key!==pendingActionRevealKey){pendingActionRevealKey=key;pendingActionRevealStarted=Date.now();clearTimeout(pendingActionRevealTimer);pendingActionRevealTimer=setTimeout(()=>{pendingActionRevealTimer=null;if(state&&actionRevealKey(state)===pendingActionRevealKey)render(state)},ACTION_REVEAL_MS+20)}}
function detectSecondChanceVisual(previous,s){if(!previous)return;for(const p of (s.players||[])){const old=previous.players?.find(x=>x.id===p.id);if(!old?.second||p.second)continue;const prefix=`${p.name}'s Second Chance blocked a duplicate `;let value=null;for(let i=(s.log||[]).length-1;i>=0&&i>=(s.log||[]).length-8;i--){const line=s.log[i]||'';if(line.startsWith(prefix)){const m=line.match(/duplicate (\d+)/);if(m)value=Number(m[1]);break}}if(value===null)continue;const token=`${s.round}|${p.id}|${s.log.length}|${value}`;secondChanceVisuals.set(p.id,{value,until:Date.now()+SECOND_CHANCE_REVEAL_MS,token});setTimeout(()=>{const current=secondChanceVisuals.get(p.id);if(current?.token!==token)return;secondChanceVisuals.delete(p.id);lastOpponentTableSig='';if(state)render(state)},SECOND_CHANCE_REVEAL_MS+20)}}
function newCardFlags(oldCards,newCards){const counts=new Map();for(const c of oldCards)counts.set(cardKey(c),(counts.get(cardKey(c))||0)+1);return newCards.map(c=>{const k=cardKey(c),n=counts.get(k)||0;if(n){counts.set(k,n-1);return false}return true})}
function fitHandRow(row,reservePreview=false){if(!row)return;const cards=[...row.children],count=cards.length;if(!count){row.style.removeProperty('--hand-scale');return}const preview=$('scorePreview'),rr=row.getBoundingClientRect(),pr=preview?.getBoundingClientRect(),reserve=reservePreview&&pr?Math.max(0,rr.right-pr.left+6):0,available=Math.max(1,row.clientWidth-16-reserve),baseWidth=window.matchMedia('(min-width:700px)').matches?84:72,stepRatio=.78,baseSpan=baseWidth*(1+(count-1)*stepRatio),scale=Math.min(1,available/baseSpan);row.style.setProperty('--hand-scale',String(scale))}
function fitPlayerHand(container){fitHandRow(container.querySelector('.hand-other'),false);fitHandRow(container.querySelector('.hand-numbers'),true)}
function ensureScorePreview(container){let preview=container.querySelector('#scorePreview');if(!preview){preview=document.createElement('div');preview.id='scorePreview';preview.className='score-preview';preview.innerHTML='<small>ROUND VALUE</small><b>0</b>';container.appendChild(preview)}return preview}
function renderHand(container,newPlayer,oldPlayer,newState=state,oldState=null){const fresh=visibleCards(newPlayer,newState),prior=visibleCards(oldPlayer,oldState),nextSig=fresh.map(cardKey).join('|'),currentSig=container.dataset.handSig||'';if(currentSig!==nextSig){const animate=oldPlayer?newCardFlags(prior,fresh):fresh.map(()=>false),other=document.createElement('div'),numbers=document.createElement('div');other.className='player-hand-row hand-other';numbers.className='player-hand-row hand-numbers';fresh.forEach((c,i)=>(c.type==='number'?numbers:other).appendChild(cardEl(c,i,animate[i])));container.innerHTML='';container.append(other,numbers);container.dataset.handSig=nextSig}ensureScorePreview(container);const result=newPlayer.busted?{cls:'bust',text:'BUST'}:newPlayer.frozen?{cls:'frozen',text:'FROZEN'}:newPlayer.stayed?{cls:'hold',text:'HOLD'}:null;container.classList.toggle('has-result',Boolean(result));let overlay=container.querySelector('.result-overlay');if(result){if(!overlay){overlay=document.createElement('div');container.appendChild(overlay)}overlay.className=`result-overlay ${result.cls}`;overlay.textContent=result.text}else if(overlay)overlay.remove();fitPlayerHand(container)}
function opponentDisplaySignature(s){const turnId=s.phase==='playing'&&!s.pendingAction?s.players[s.turnIndex]?.id||'':'';return `${turnId}::`+s.players.filter(p=>p.id!==myId).map(p=>[p.id,p.name,handSignature(p,s),p.busted?1:0,p.frozen?1:0,p.stayed?1:0,p.roundScore||0].join('~')).join('||')}
function renderOpponentTable(s,previous){const table=$('botTable');if(!table)return;const sig=opponentDisplaySignature(s);if(sig===lastOpponentTableSig)return;lastOpponentTableSig=sig;const previousById=new Map((previous?.players||[]).map(p=>[p.id,p]));const turnId=s.phase==='playing'&&!s.pendingAction?s.players[s.turnIndex]?.id:null;table.innerHTML='';s.players.filter(p=>p.id!==myId).forEach(p=>{const old=previousById.get(p.id);const seat=document.createElement('div');seat.dataset.playerId=p.id;seat.className=`bot-seat ${p.id===turnId?'turn':''} ${p.busted?'busted':''} ${p.stayed?'banked':''} ${p.frozen?'frozen':''} ${(p.busted||p.stayed||p.frozen)?'has-result':''} ${p.voiceEnabled?'voice-on':''} ${p.voiceSpeaking?'voice-speaking':''}`.trim();const head=document.createElement('div');head.className='bot-seat-head';const name=document.createElement('b');name.textContent=p.name+(p.computer?' 🤖':'');const status=document.createElement('small');status.textContent=p.busted?'BUST':p.frozen?'FROZEN':p.cards.length>=7?'7-CARD +15':p.stayed?'HOLD':`${calculatePreview(p)} pts`;head.append(name,status);const hand=document.createElement('div');hand.className='bot-hand';const fresh=visibleCards(p,s),prior=visibleCards(old,previous),animate=old?newCardFlags(prior,fresh):fresh.map(()=>false);fresh.forEach((c,i)=>hand.appendChild(cardEl(c,i,animate[i])));seat.append(head,hand);if(p.busted||p.frozen||p.stayed){const overlay=document.createElement('div');overlay.className=`result-overlay ${p.busted?'bust':p.frozen?'frozen':'hold'}`;overlay.textContent=p.busted?'BUST':p.frozen?'FROZEN':'HOLD';seat.appendChild(overlay)}table.appendChild(seat)})}

function renderVoiceSeatStates(s){const table=$('botTable');if(!table)return;const byId=new Map((s.players||[]).map(p=>[p.id,p]));for(const seat of table.children){const p=byId.get(seat.dataset.playerId);if(!p)continue;seat.classList.toggle('voice-on',Boolean(p.voiceEnabled));seat.classList.toggle('voice-speaking',Boolean(p.voiceSpeaking))}}

function renderTargetPicker(s){const p=$('targetPicker'),a=s.pendingAction;if(!a||a.chooserId!==myId||actionRevealActive(s)){p.classList.add('hidden');p.innerHTML='';return}const eligible=s.players.filter(x=>a.eligibleIds.includes(x.id));p.classList.remove('hidden');p.innerHTML=`<div class="target-title">Choose who receives <b>${actionName(a.card.name)}</b></div><div class="target-list"></div>`;const list=p.querySelector('.target-list');eligible.forEach(x=>{const b=document.createElement('button');b.className='target';b.innerHTML=`<span>${esc(x.name)}</span><small>${x.id===myId?'YOU':`${x.cards.length} NUMBER CARDS`}</small>`;b.onclick=()=>{haptic();api('target',{targetId:x.id}).catch(e=>toast(e.message))};list.appendChild(b)})}
function confetti(){const root=$('confetti'),colors=['#32e5cb','#ffdd42','#ff4f8b','#8e7dff','#fff'];root.innerHTML='';for(let i=0;i<70;i++){const x=document.createElement('i');x.className='confetti-piece';x.style.left=Math.random()*100+'%';x.style.background=colors[i%colors.length];x.style.animationDelay=Math.random()*.8+'s';x.style.animationDuration=1.8+Math.random()*1.4+'s';root.appendChild(x)}setTimeout(()=>root.innerHTML='',3500)}
function showSevenBonus(player){const flash=$('bonusFlash');if(!flash||!player)return;flash.innerHTML=`${esc(player.name)} reached 7 number cards!<b>+15</b>`;flash.classList.remove('show');void flash.offsetWidth;flash.classList.add('show');confetti();tone(820,.14,'triangle');setTimeout(()=>tone(1040,.18,'triangle'),120);haptic(22);setTimeout(()=>flash.classList.remove('show'),2200)}
function showWinnerPopup(s){if(!s||s.phase!=='gameOver')return;const standings=[...(s.players||[])].sort((a,b)=>b.score-a.score),winner=standings[0];if(!winner)return;const isHost=s.hostId===myId,rematch=isHost?'<button id="playAgain" class="menu-action play-again" aria-label="Play another game">↻ PLAY AGAIN</button>':'<p style="margin:18px 0 0;color:#8ea4b7">Waiting for the host to play again…</p>';$('closeModal').classList.add('hidden');$('modalBody').innerHTML=`<div style="text-align:center;padding:18px 4px"><div style="font-size:58px">🏆</div><div style="font:900 15px 'Archivo Black';letter-spacing:.18em;color:#32e5cb;margin-top:8px">GAME OVER</div><h2 style="font-size:42px;margin:10px 0;color:#ffdd42">${esc(s.winner||winner.name)} WINS!</h2><p style="font-size:18px;color:white">Final score: <b>${winner.score}</b> points</p><div style="margin:18px 0;padding:14px;border-radius:18px;background:#07111d">${standings.map((p,i)=>`<div style="display:flex;justify-content:space-between;padding:7px 4px;color:${i===0?'#ffdd42':'#dcecff'}"><span>${i+1}. ${esc(p.name)}${p.computer?' 🤖':''}</span><b>${p.score}</b></div>`).join('')}</div>${rematch}</div>`;$('modal').dataset.mode='winner';$('modal').classList.remove('hidden');if(isHost)setTimeout(()=>{const button=$('playAgain');if(button)button.onclick=async()=>{button.disabled=true;button.textContent='STARTING…';try{await api('restart');closeModal()}catch(error){button.disabled=false;button.textContent='↻ PLAY AGAIN';toast(error.message)}}},0);confetti();tone(740,.3);setTimeout(()=>tone(980,.35),180)}
function findNewFlip7(previous,s){if(!previous||!s)return null;for(const p of (s.players||[])){const old=previous.players?.find(x=>x.id===p.id);if((p.cards?.length||0)>=7&&(old?.cards?.length||0)<7)return p}return null}
function latestReactionFor(s,playerId){const reactions=s.reactions||[];for(let i=reactions.length-1;i>=0;i--)if(reactions[i].playerId===playerId)return reactions[i];return null}
function showReaction(reaction,s){if(!reaction||seenReactions.has(reaction.id))return;seenReactions.add(reaction.id);if(seenReactions.size>80){const first=seenReactions.values().next().value;seenReactions.delete(first)}const sender=s.players.find(p=>p.id===reaction.playerId);const pop=$('reactionPop');if(!pop)return;pop.innerHTML=`<span>${esc(reaction.emoji)}</span><div><b>${esc(sender?.name||'Player')}</b><small>SENT A REACTION</small></div>`;pop.classList.remove('show');void pop.offsetWidth;pop.classList.add('show');clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>pop.classList.remove('show'),2600);if(reaction.playerId!==myId){tone(490,.07,'triangle');haptic(10)}}
function renderNewReactions(s){const reactions=s.reactions||[];if(!reactions.length)return;for(const reaction of reactions)showReaction(reaction,s)}
function showPhrase(message,s){if(!message||seenPhrases.has(message.id))return;seenPhrases.add(message.id);if(seenPhrases.size>80){const first=seenPhrases.values().next().value;seenPhrases.delete(first)}const sender=s.players.find(p=>p.id===message.playerId);const pop=$('phrasePop');if(!pop)return;pop.innerHTML=`<b>${esc(sender?.name||'Player')} SAYS</b><strong>${esc(message.phrase)}</strong>`;pop.classList.remove('show');void pop.offsetWidth;pop.classList.add('show');clearTimeout(phraseTimer);phraseTimer=setTimeout(()=>pop.classList.remove('show'),3000);if(message.playerId!==myId){tone(610,.09,'triangle');setTimeout(()=>tone(760,.08,'triangle'),90);haptic(14)}}
function renderNewPhrases(s){for(const message of (s.phrases||[]))showPhrase(message,s)}
function openPhraseTray(){const tray=$('phraseTray'),me=state?.players?.find(p=>p.id===myId);const phrases=[...QUICK_PHRASES];if((me?.name||'').trim().toLowerCase()==='becca')phrases.push(BECCA_PHRASE);tray.innerHTML=phrases.map(phrase=>`<button data-phrase="${esc(phrase)}" class="${phrase===BECCA_PHRASE?'becca-phrase':''}">${esc(phrase)}</button>`).join('');$('reactionTray').classList.add('hidden');tray.classList.toggle('hidden')}

function statusText(s,myTurn){if(s.pendingAction){const c=s.players.find(p=>p.id===s.pendingAction.chooserId);if(actionRevealActive(s))return[`${c?.name||'PLAYER'} DREW ${actionName(s.pendingAction.card.name)}`,'Action card revealed'];return[c?.id===myId?`CHOOSE A TARGET FOR ${actionName(s.pendingAction.card.name)}`:`${c?.name} IS CHOOSING A TARGET`,'Action card in play']}if(s.phase==='lobby')return[`WAITING FOR PLAYERS (${s.players.length}/9)`,'Share the room code to invite friends'];if(s.dealing)return['DEALING OPENING CARDS','Cards are being dealt one at a time'];if(s.actionCardVisual){const visual=s.actionCardVisual,giver=s.players.find(p=>p.id===visual.fromId),target=s.players.find(p=>p.id===visual.targetId),label=actionName(visual.name);if(visual.stage==='giver'&&visual.fromId!==visual.targetId)return[`${giver?.name||'PLAYER'} GIVES ${label}`,`Moving to ${target?.name||'the chosen player'}`];if(visual.outcome==='discard')return[`${giver?.name||'PLAYER'} REVEALS ${label}`,'No eligible recipient — moving to discard'];return[`${target?.name||'PLAYER'} RECEIVES ${label}`,visual.name==='freeze'?'Freeze will remain with that player this round':'Protection is being added to that hand']}if(s.flipThreeVisual){const giver=s.players.find(p=>p.id===s.flipThreeVisual.fromId),target=s.players.find(p=>p.id===s.flipThreeVisual.targetId);return s.flipThreeVisual.stage==='giver'?[`${giver?.name||'PLAYER'} GIVES FLIP THREE`,`Moving to ${target?.name||'the chosen player'}`]:[`${target?.name||'PLAYER'} RECEIVES FLIP THREE`,'Three cards are being revealed one at a time']}if(s.resolvingAction)return['ACTION CARD IN PROGRESS','Watch the card move to its recipient'];if(s.phase==='playing')return[myTurn?'YOUR DECISION — FLIP OR HOLD':`${s.players[s.turnIndex]?.name}'S TURN`,myTurn?'How far will you push it?':'Watch the table'];if(s.phase==='roundEnd')return['ROUND COMPLETE','Scores have been banked'];return[`${s.winner} WINS!`,'Game complete']}
function render(s){const previous=state;state=s;rememberPastPlayers(s);if(s.phase!=='gameOver'&&$('modal').dataset.mode==='winner')closeModal();detectSecondChanceVisual(previous,s);updateActionReveal(s);$('copyCode').querySelector('b').textContent=s.code;$('round').textContent=s.round;$('deckCount').textContent=s.deckCount;renderDiscardPile(s);const me=s.players.find(p=>p.id===myId),oldMe=previous?.players?.find(p=>p.id===myId),frozeNow=Boolean(previous&&me?.frozen&&!oldMe?.frozen),bustedNow=Boolean(previous&&me?.busted&&!oldMe?.busted),turn=s.players[s.turnIndex],myTurn=s.phase==='playing'&&!s.dealing&&!s.resolvingAction&&!s.pendingAction&&turn?.id===myId;document.body.classList.toggle('my-turn',myTurn);
$('players').innerHTML='';s.players.forEach((p,i)=>{const e=document.createElement('div');e.className='player '+(s.phase==='playing'&&!s.pendingAction&&i===s.turnIndex?'turn ':'')+(p.voiceEnabled?'voice-on ':'')+(p.voiceSpeaking?'voice-speaking':'');e.dataset.playerId=p.id;const live=p.busted?'BUSTED':p.frozen?`FROZEN ${p.roundScore}`:p.stayed?`BANKED ${p.roundScore}`:`${p.cards.length} NUMBERS`;const reaction=latestReactionFor(s,p.id);e.innerHTML=`<span class="dot ${p.connected?'':'off'}"></span>${reaction?`<div class="player-reaction">${esc(reaction.emoji)}</div>`:''}<div class="avatar" style="background:${avatarColors[i%avatarColors.length]}">${esc(p.name.charAt(0).toUpperCase())}</div><div class="name">${esc(p.name)}${p.computer?' 🤖':''}${p.id===s.hostId?' ★':''}${i===s.dealerIndex?' ◇':''}</div><div class="score">${p.score}</div><small>${live}${p.second?' · 2ND CHANCE':''}</small>`;$('players').appendChild(e)});
const area=$('myArea');if(me)renderHand(area,me,oldMe,s,previous);else{area.innerHTML='';area.dataset.handSig='';ensureScorePreview(area)}renderOpponentTable(s,previous);renderVoiceSeatStates(s);ensureScorePreview(area).querySelector('b').textContent=calculatePreview(me);syncFlipThreeTransfer(s);syncActionCardTransfer(s);
renderTargetPicker(s);$('hit').disabled=!myTurn;$('stay').disabled=!myTurn||!(me&&(me.cards.length||me.mods.length||me.second));$('hit').classList.toggle('hidden',s.phase!=='playing'||!!s.pendingAction);$('stay').classList.toggle('hidden',s.phase!=='playing'||!!s.pendingAction);$('start').classList.toggle('hidden',!(s.phase==='lobby'&&s.hostId===myId));$('next').classList.toggle('hidden',!(s.phase==='roundEnd'&&s.hostId===myId));$('lobbyCard').classList.toggle('hidden',s.phase!=='lobby');$('table').classList.toggle('hidden',s.phase==='lobby');
const [big,small]=statusText(s,myTurn);$('status').innerHTML=`<span class="pulse"></span><b>${esc(big)}</b><small>${esc(small)}</small>`;$('log').innerHTML=s.log.map(x=>`<div>${esc(x)}</div>`).join('');
renderNewReactions(s);renderNewPhrases(s);syncVoicePeers(s);
if(previous){const newCount=(me?.cards.length||0)+(me?.mods.length||0)+(me?.second?1:0),oldCount=(oldMe?.cards.length||0)+(oldMe?.mods.length||0)+(oldMe?.second?1:0);if(newCount>oldCount){tone(680,.08,'triangle');haptic(12)}const flip7Player=findNewFlip7(previous,s);if(flip7Player)showSevenBonus(flip7Player);if(previous.phase!=='gameOver'&&s.phase==='gameOver'){if(flip7Player)setTimeout(()=>showWinnerPopup(s),2300);else showWinnerPopup(s)}}else if(s.phase==='gameOver'){setTimeout(()=>showWinnerPopup(s),120)}if(bustedNow)showLocalScreenEffect('bust');else if(frozeNow)showLocalScreenEffect('freeze');lastPhase=s.phase}
function showModal(html,mode=''){$('modalBody').innerHTML=html;$('modal').classList.remove('hidden');if(mode==='leave')setTimeout(()=>{const b=$('confirmLeave');if(b)b.onclick=leave},0)}
function closeModal(){$('modal').classList.add('hidden');$('modal').dataset.mode='';$('closeModal').classList.remove('hidden')}
$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()}
const help=`<h2>How to play</h2><p>Build the highest score without revealing a duplicate number.</p><ol><li>On your turn, choose <b>Flip</b> to draw or <b>Stay</b> to bank your round value.</li><li>A duplicate number busts your round unless a Second Chance protects you. You may hold only one Second Chance; if you draw another, give it to another active player who does not have one, or discard it if nobody can receive it.</li><li>Second Chance protects only against a duplicate Number card. It does not block Freeze.</li><li>Freeze and Flip Three may target any active player, including yourself.</li><li>During Flip Three, all three revealed cards count unless the target busts or reaches Flip 7. A Second Chance resolves immediately; other Action cards wait until the three-card sequence finishes.</li><li>Seven unique Number cards immediately end the round and award a 15-point bonus. ×2 doubles only the Number-card subtotal; additive modifiers and the +15 bonus are added afterward.</li><li>Once the high score is at least 200, the highest total wins. If the highest score is tied, everyone plays another full round.</li><li>In multiplayer, tap the microphone button to join voice chat. It starts muted and only broadcasts after you grant microphone permission and turn it on.</li></ol><button class="menu-action" onclick="document.getElementById('modal').classList.add('hidden')">GOT IT</button>`;
$('howBtn').onclick=()=>showModal(help);$('menuBtn').onclick=()=>showModal(`<h2>Game menu</h2><button class="menu-action" id="menuHow">HOW TO PLAY</button><button class="menu-action" id="menuSound">${soundOn?'MUTE SOUND':'TURN SOUND ON'}</button><button class="menu-action" id="menuLeave">LEAVE ROOM</button>`);$('modalBody').addEventListener('click',e=>{if(e.target.id==='menuHow')showModal(help);if(e.target.id==='menuSound'){soundOn=!soundOn;localStorage.fr7sound=soundOn?'on':'off';toast(soundOn?'Sound on':'Sound muted');closeModal()}if(e.target.id==='menuLeave')leave()});
$('soundBtn').onclick=()=>{soundOn=!soundOn;localStorage.fr7sound=soundOn?'on':'off';$('soundBtn').textContent=soundOn?'♪':'×';if(soundOn)tone(520,.08)};$('soundBtn').textContent=soundOn?'♪':'×';
$('micBtn').onclick=toggleVoice;updateMicButton();window.addEventListener('pagehide',voicePageHide);
$('react').onclick=()=>{haptic(8);$('phraseTray').classList.add('hidden');$('reactionTray').classList.toggle('hidden')};$('reactionTray').onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.id==='phraseMenuBtn'){haptic(8);openPhraseTray();return}const emoji=button.dataset.emoji;if(!emoji)return;$('reactionTray').classList.add('hidden');haptic(8);api('react',{emoji}).then(()=>{toast(`${emoji} sent to everyone`);tone(420,.05)}).catch(err=>toast(err.message))};$('phraseTray').onclick=e=>{const button=e.target.closest('button[data-phrase]');if(!button)return;const phrase=button.dataset.phrase;$('phraseTray').classList.add('hidden');haptic(8);api('phrase',{phrase}).then(()=>{toast('Phrase sent to everyone');tone(520,.06)}).catch(err=>toast(err.message))};
if(room&&myId){api('state').then(()=>enter()).catch(()=>{localStorage.removeItem('fr7room');localStorage.removeItem('fr7pid');room='';myId='';home.classList.add('active');game.classList.remove('active')})}
window.addEventListener('load',()=>{if(pushSupported()&&Notification.permission==='granted')setTimeout(()=>ensurePushRegistration(false),500)});
setInterval(()=>{if(room&&myId)api('state').catch(()=>{})},800);window.addEventListener('resize',()=>{const area=$('myArea');if(area)fitPlayerHand(area)});
