let state=null,myId=localStorage.fr7pid||'',room=localStorage.fr7room||'',lastCardCount=0,lastPhase='',soundOn=localStorage.fr7sound!=='off',pollFailures=0,reactionTimer=null,phraseTimer=null,lastOpponentTableSig='';
let voiceOn=false,voiceSpeaking=false,localVoiceStream=null,voiceContext=null,voiceAnalyser=null,voiceMonitorFrame=0,voiceSignalTimer=null,lastVoiceActivity=0;
const voicePeers=new Map();
const seenReactions=new Set(),seenPhrases=new Set();
const QUICK_PHRASES=['Nice Job!',"You're almost there!",'So Close!','You suck!','Oh Man!'];
const BECCA_PHRASE="You're a peckerhead!";
const $=id=>document.getElementById(id),home=$('home'),game=$('game'),err=$('error');
const avatarColors=['#32e5cb','#ffdd42','#ff6f91','#8e7dff','#ff914d','#72d7ff'];
function haptic(ms=18){if(navigator.vibrate)navigator.vibrate(ms)}
function tone(freq=440,duration=.08,type='sine',gain=.05){if(!soundOn)return;try{const C=window.AudioContext||window.webkitAudioContext,a=new C(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.stop(a.currentTime+duration)}catch{}}
function voiceSupported(){return Boolean(navigator.mediaDevices?.getUserMedia&&window.RTCPeerConnection)}
function updateMicButton(){const b=$('micBtn');if(!b)return;b.classList.toggle('voice-on',voiceOn);b.classList.toggle('voice-speaking',voiceOn&&voiceSpeaking);b.setAttribute('aria-label',voiceOn?'Mute microphone':'Turn microphone on');b.title=voiceOn?(voiceSpeaking?'Microphone on — you are speaking':'Microphone on — tap to mute'):'Microphone off';if(!voiceSupported()){b.disabled=true;b.title='Voice chat is not supported on this device'}}
async function voicePost(path,data={}){const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room,playerId:myId,...data}),cache:'no-store'});const json=await response.json();if(!json.ok)throw new Error(json.error||'Voice chat error');return json}
function voiceStatus(enabled,speaking=false){if(!room||!myId)return Promise.resolve();return voicePost('voice-status',{enabled:Boolean(enabled),speaking:Boolean(enabled&&speaking)}).catch(()=>{})}
function closeVoicePeer(peerId){const entry=voicePeers.get(peerId);if(!entry)return;voicePeers.delete(peerId);entry.closing=true;try{entry.pc.onconnectionstatechange=null;entry.pc.onicecandidate=null;entry.pc.ontrack=null;entry.pc.close()}catch{}try{entry.audio.pause();entry.audio.srcObject=null;entry.audio.remove()}catch{}}
function closeAllVoicePeers(){for(const peerId of [...voicePeers.keys()])closeVoicePeer(peerId)}
async function sendVoiceSignal(targetId,signal){try{await voicePost('voice-signal',{targetId,signal})}catch(e){if(voiceOn&&String(e.message||'').includes('enable voice'))return}}
function serialDescription(description){return description?.toJSON?description.toJSON():description}
function serialCandidate(candidate){return candidate?.toJSON?candidate.toJSON():candidate}
function makeVoicePeer(peerId){if(voicePeers.has(peerId))return voicePeers.get(peerId);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});const audio=document.createElement('audio');audio.autoplay=true;audio.playsInline=true;audio.dataset.voicePeer=peerId;$('voiceAudioRack')?.appendChild(audio);const entry={pc,audio,pendingCandidates:[],offerStarted:false,closing:false};voicePeers.set(peerId,entry);for(const track of (localVoiceStream?.getTracks()||[]))pc.addTrack(track,localVoiceStream);pc.onicecandidate=event=>{if(event.candidate&&voiceOn)sendVoiceSignal(peerId,{type:'candidate',candidate:serialCandidate(event.candidate)})};pc.ontrack=event=>{const stream=event.streams?.[0]||new MediaStream([event.track]);audio.srcObject=stream;audio.play().catch(()=>{})};pc.onconnectionstatechange=()=>{if(entry.closing)return;if(pc.connectionState==='failed'||pc.connectionState==='closed'){closeVoicePeer(peerId);setTimeout(()=>{const remote=state?.players?.find(p=>p.id===peerId);if(voiceOn&&remote?.voiceEnabled&&remote?.connected)ensureVoicePeer(peerId)},900)}};return entry}
async function startVoiceOffer(peerId,entry){if(!voiceOn||entry.offerStarted||entry.pc.signalingState!=='stable')return;entry.offerStarted=true;try{const offer=await entry.pc.createOffer({offerToReceiveAudio:true});await entry.pc.setLocalDescription(offer);await sendVoiceSignal(peerId,{type:'offer',description:serialDescription(entry.pc.localDescription)})}catch{entry.offerStarted=false}}
function ensureVoicePeer(peerId){if(!voiceOn||peerId===myId)return null;const entry=makeVoicePeer(peerId);if(myId<peerId)startVoiceOffer(peerId,entry);return entry}
async function flushVoiceCandidates(entry){if(!entry.pc.remoteDescription)return;while(entry.pendingCandidates.length){const candidate=entry.pendingCandidates.shift();try{await entry.pc.addIceCandidate(candidate)}catch{}}}
async function handleVoiceSignal(message){if(!voiceOn||!message?.fromId||!message.signal)return;const peerId=message.fromId,signal=message.signal,entry=ensureVoicePeer(peerId);if(!entry)return;const pc=entry.pc;try{if(signal.type==='offer'){await pc.setRemoteDescription(signal.description);await flushVoiceCandidates(entry);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await sendVoiceSignal(peerId,{type:'answer',description:serialDescription(pc.localDescription)})}else if(signal.type==='answer'){if(pc.signalingState==='have-local-offer'){await pc.setRemoteDescription(signal.description);await flushVoiceCandidates(entry)}}else if(signal.type==='candidate'&&signal.candidate){if(pc.remoteDescription)await pc.addIceCandidate(signal.candidate);else entry.pendingCandidates.push(signal.candidate)}}catch{}}
async function pollVoiceSignals(){if(!voiceOn||!room||!myId)return;try{const q=new URLSearchParams({room,playerId:myId});const response=await fetch('/api/voice-signals?'+q.toString(),{cache:'no-store'});const json=await response.json();if(json.ok)for(const message of (json.signals||[]))await handleVoiceSignal(message)}catch{}}
function startVoiceSignalPolling(){clearInterval(voiceSignalTimer);pollVoiceSignals();voiceSignalTimer=setInterval(pollVoiceSignals,320)}
function stopVoiceMonitor(){if(voiceMonitorFrame)cancelAnimationFrame(voiceMonitorFrame);voiceMonitorFrame=0;if(voiceContext){voiceContext.close().catch(()=>{});voiceContext=null}voiceAnalyser=null;voiceSpeaking=false;updateMicButton()}
function startVoiceMonitor(stream){stopVoiceMonitor();try{const C=window.AudioContext||window.webkitAudioContext;voiceContext=new C();voiceContext.resume?.().catch(()=>{});const source=voiceContext.createMediaStreamSource(stream);voiceAnalyser=voiceContext.createAnalyser();voiceAnalyser.fftSize=512;source.connect(voiceAnalyser);const data=new Uint8Array(voiceAnalyser.fftSize);lastVoiceActivity=0;const frame=()=>{if(!voiceOn||!voiceAnalyser)return;voiceAnalyser.getByteTimeDomainData(data);let sum=0;for(const v of data){const n=(v-128)/128;sum+=n*n}const rms=Math.sqrt(sum/data.length),now=Date.now();if(rms>.035)lastVoiceActivity=now;const talking=lastVoiceActivity>0&&now-lastVoiceActivity<280;if(talking!==voiceSpeaking){voiceSpeaking=talking;updateMicButton();voiceStatus(true,voiceSpeaking)}voiceMonitorFrame=requestAnimationFrame(frame)};voiceMonitorFrame=requestAnimationFrame(frame)}catch{}}
function syncVoicePeers(s){if(!voiceOn)return;const wanted=new Set((s.players||[]).filter(p=>p.id!==myId&&p.connected&&p.voiceEnabled).map(p=>p.id));for(const peerId of wanted)ensureVoicePeer(peerId);for(const peerId of [...voicePeers.keys()])if(!wanted.has(peerId))closeVoicePeer(peerId)}
async function enableVoice(){if(voiceOn)return;if(!voiceSupported()){toast('Voice chat is not supported on this device');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});localVoiceStream=stream;voiceOn=true;voiceSpeaking=false;updateMicButton();startVoiceMonitor(stream);await voiceStatus(true,false);startVoiceSignalPolling();try{const result=await api('state');syncVoicePeers(result.state)}catch{}toast('Microphone on — voice chat ready');haptic(12)}catch(e){voiceOn=false;updateMicButton();const denied=e?.name==='NotAllowedError'||e?.name==='SecurityError';toast(denied?'Microphone permission was not allowed':'Could not start microphone')}}
function disableVoice(notify=true){if(!voiceOn&&!localVoiceStream)return;voiceOn=false;voiceSpeaking=false;clearInterval(voiceSignalTimer);voiceSignalTimer=null;stopVoiceMonitor();closeAllVoicePeers();for(const track of (localVoiceStream?.getTracks()||[]))try{track.stop()}catch{}localVoiceStream=null;voiceStatus(false,false);updateMicButton();if(notify){toast('Microphone muted');haptic(8)}}
function toggleVoice(){if(voiceOn)disableVoice();else enableVoice()}
function voicePageHide(){if(voiceOn&&room&&myId){try{const blob=new Blob([JSON.stringify({room,playerId:myId,enabled:false,speaking:false})],{type:'application/json'});navigator.sendBeacon('/api/voice-status',blob)}catch{}}for(const track of (localVoiceStream?.getTracks()||[]))try{track.stop()}catch{}}
async function api(path,data={}){try{const isState=path==='state';let url='/api/'+path;const options={method:isState?'GET':'POST',headers:{'Content-Type':'application/json'}};if(isState){const params=new URLSearchParams({room,playerId:myId});url+='?'+params.toString()}else{const payload={...data};if(path!=='create'&&path!=='join'){payload.room=room;payload.playerId=myId}options.body=JSON.stringify(payload)}const response=await fetch(url,options);const json=await response.json();if(!json.ok)throw new Error(json.error);pollFailures=0;$('connection').classList.add('hidden');if(json.state)render(json.state);return json}catch(e){pollFailures++;if(pollFailures>2&&room)$('connection').classList.remove('hidden');throw e}}
function enter(){home.classList.remove('active');game.classList.add('active')}
function leave(){disableVoice(false);localStorage.removeItem('fr7room');localStorage.removeItem('fr7pid');location.reload()}
$('create').onclick=async()=>{try{const r=await api('create',{name:$('name').value.trim()||'Host'});room=r.room;myId=r.playerId;localStorage.fr7room=room;localStorage.fr7pid=myId;enter();render(r.state);tone(520,.09)}catch(e){err.textContent=e.message}}
$('join').onclick=async()=>{try{const r=await api('join',{name:$('name').value.trim()||'Player',room:$('roomCode').value});room=r.room;myId=r.playerId;localStorage.fr7room=room;localStorage.fr7pid=myId;enter();render(r.state);tone(520,.09)}catch(e){err.textContent=e.message}}
$('roomCode').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''));
for(const [id,path] of [['hit','hit'],['stay','stay'],['start','start'],['next','next']])$(id).onclick=()=>{haptic();tone(id==='stay'?310:560,.07,id==='hit'?'square':'sine');api(path).catch(e=>toast(e.message))};
$('leave').onclick=()=>showModal(`<h2>Leave the table?</h2><p>You can return while the room is still active using the same device.</p><button class="menu-action" id="confirmLeave">LEAVE ROOM</button>`,'leave');
$('copyCode').onclick=shareRoom;$('share').onclick=shareRoom;
async function shareRoom(){const text=`Join my Flip Rush 7 room: ${state.code}`;try{if(navigator.share)await navigator.share({title:'Flip Rush 7',text});else{await navigator.clipboard.writeText(state.code);toast('Room code copied')}}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1700)}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function actionName(n){return n==='freeze'?'FREEZE':n==='flip3'?'FLIP THREE':'SECOND CHANCE'}
function calculatePreview(p){if(!p||p.busted)return 0;let n=p.cards.reduce((s,c)=>s+c.value,0);if(p.mods.some(c=>c.type==='multiplier'))n*=2;n+=p.mods.filter(c=>c.type==='modifier').reduce((s,c)=>s+c.value,0);if(p.cards.length>=7)n+=15;return n}
function cardEl(card,index=0,animate=true){const e=document.createElement('div');e.className='card';e.style.animationDelay=`${Math.min(index*25,160)}ms`;if(!animate)e.style.animation='none';if(card.type==='number'){e.textContent=card.value;e.dataset.label=card.value;e.classList.add('number',`n${card.value}`)}else if(card.type==='modifier'){e.textContent='+'+card.value;e.classList.add('mod');e.dataset.label='BONUS'}else if(card.type==='multiplier'){e.textContent='×2';e.classList.add('mult');e.dataset.label='BOOST'}else{e.textContent=actionName(card.name);e.classList.add('action',card.name);e.dataset.label='ACTION'}return e}
function cardSortRank(c){if(c.type==='number')return c.value;if(c.type==='modifier')return 100+c.value;if(c.type==='multiplier')return 200;if(c.type==='action'&&c.name==='second')return 300;return 400}
function visibleCards(p){return p?[...p.cards,...p.mods,...(p.second?[{type:'action',name:'second'}]:[])].sort((a,b)=>cardSortRank(a)-cardSortRank(b)):[]}
function cardKey(c){return `${c.type}:${c.name||''}:${c.value??''}`}
function handSignature(p){return visibleCards(p).map(cardKey).join('|')}
function newCardFlags(oldCards,newCards){const counts=new Map();for(const c of oldCards)counts.set(cardKey(c),(counts.get(cardKey(c))||0)+1);return newCards.map(c=>{const k=cardKey(c),n=counts.get(k)||0;if(n){counts.set(k,n-1);return false}return true})}
function fitHandRow(row,reservePreview=false){if(!row)return;const cards=[...row.children],count=cards.length;if(!count){row.style.removeProperty('--hand-scale');return}const preview=$('scorePreview'),rr=row.getBoundingClientRect(),pr=preview?.getBoundingClientRect(),reserve=reservePreview&&pr?Math.max(0,rr.right-pr.left+6):0,available=Math.max(1,row.clientWidth-16-reserve),baseWidth=window.matchMedia('(min-width:700px)').matches?84:72,stepRatio=.78,baseSpan=baseWidth*(1+(count-1)*stepRatio),scale=Math.min(1,available/baseSpan);row.style.setProperty('--hand-scale',String(scale))}
function fitPlayerHand(container){fitHandRow(container.querySelector('.hand-other'),false);fitHandRow(container.querySelector('.hand-numbers'),true)}
function renderHand(container,newPlayer,oldPlayer){const fresh=visibleCards(newPlayer),prior=visibleCards(oldPlayer),nextSig=fresh.map(cardKey).join('|'),currentSig=container.dataset.handSig||'';if(currentSig!==nextSig){const animate=oldPlayer?newCardFlags(prior,fresh):fresh.map(()=>false),other=document.createElement('div'),numbers=document.createElement('div');other.className='player-hand-row hand-other';numbers.className='player-hand-row hand-numbers';fresh.forEach((c,i)=>(c.type==='number'?numbers:other).appendChild(cardEl(c,i,animate[i])));container.innerHTML='';container.append(other,numbers);container.dataset.handSig=nextSig}fitPlayerHand(container)}
function opponentDisplaySignature(s){const turnId=s.phase==='playing'&&!s.pendingAction?s.players[s.turnIndex]?.id||'':'';return `${turnId}::`+s.players.filter(p=>p.id!==myId).map(p=>[p.id,p.name,handSignature(p),p.busted?1:0,p.frozen?1:0,p.stayed?1:0,p.roundScore||0].join('~')).join('||')}
function renderOpponentTable(s,previous){const table=$('botTable');if(!table)return;const sig=opponentDisplaySignature(s);if(sig===lastOpponentTableSig)return;lastOpponentTableSig=sig;const previousById=new Map((previous?.players||[]).map(p=>[p.id,p]));const turnId=s.phase==='playing'&&!s.pendingAction?s.players[s.turnIndex]?.id:null;table.innerHTML='';s.players.filter(p=>p.id!==myId).forEach(p=>{const old=previousById.get(p.id);const seat=document.createElement('div');seat.dataset.playerId=p.id;seat.className=`bot-seat ${p.id===turnId?'turn':''} ${p.busted?'busted':''} ${p.stayed?'banked':''} ${p.frozen?'frozen':''} ${(p.busted||p.stayed||p.frozen)?'has-result':''} ${p.voiceEnabled?'voice-on':''} ${p.voiceSpeaking?'voice-speaking':''}`.trim();const head=document.createElement('div');head.className='bot-seat-head';const name=document.createElement('b');name.textContent=p.name;const status=document.createElement('small');status.textContent=p.busted?'BUST':p.frozen?'FROZEN':p.cards.length>=7?'7-CARD +15':p.stayed?'HOLD':`${calculatePreview(p)} pts`;head.append(name,status);const hand=document.createElement('div');hand.className='bot-hand';const fresh=visibleCards(p),prior=visibleCards(old),animate=old?newCardFlags(prior,fresh):fresh.map(()=>false);fresh.forEach((c,i)=>hand.appendChild(cardEl(c,i,animate[i])));seat.append(head,hand);if(p.busted||p.frozen||p.stayed){const overlay=document.createElement('div');overlay.className=`result-overlay ${p.busted?'bust':p.frozen?'frozen':'hold'}`;overlay.textContent=p.busted?'BUST':p.frozen?'FROZEN':'HOLD';seat.appendChild(overlay)}table.appendChild(seat)})}

function renderVoiceSeatStates(s){const table=$('botTable');if(!table)return;const byId=new Map((s.players||[]).map(p=>[p.id,p]));for(const seat of table.children){const p=byId.get(seat.dataset.playerId);if(!p)continue;seat.classList.toggle('voice-on',Boolean(p.voiceEnabled));seat.classList.toggle('voice-speaking',Boolean(p.voiceSpeaking))}}

function renderTargetPicker(s){const p=$('targetPicker'),a=s.pendingAction;if(!a||a.chooserId!==myId){p.classList.add('hidden');p.innerHTML='';return}const eligible=s.players.filter(x=>a.eligibleIds.includes(x.id));p.classList.remove('hidden');p.innerHTML=`<div class="target-title">Choose who receives <b>${actionName(a.card.name)}</b></div><div class="target-list"></div>`;const list=p.querySelector('.target-list');eligible.forEach(x=>{const b=document.createElement('button');b.className='target';b.innerHTML=`<span>${esc(x.name)}</span><small>${x.id===myId?'YOU':`${x.cards.length} NUMBER CARDS`}</small>`;b.onclick=()=>{haptic();api('target',{targetId:x.id}).catch(e=>toast(e.message))};list.appendChild(b)})}
function confetti(){const root=$('confetti'),colors=['#32e5cb','#ffdd42','#ff4f8b','#8e7dff','#fff'];root.innerHTML='';for(let i=0;i<70;i++){const x=document.createElement('i');x.className='confetti-piece';x.style.left=Math.random()*100+'%';x.style.background=colors[i%colors.length];x.style.animationDelay=Math.random()*.8+'s';x.style.animationDuration=1.8+Math.random()*1.4+'s';root.appendChild(x)}setTimeout(()=>root.innerHTML='',3500)}
function latestReactionFor(s,playerId){const reactions=s.reactions||[];for(let i=reactions.length-1;i>=0;i--)if(reactions[i].playerId===playerId)return reactions[i];return null}
function showReaction(reaction,s){if(!reaction||seenReactions.has(reaction.id))return;seenReactions.add(reaction.id);if(seenReactions.size>80){const first=seenReactions.values().next().value;seenReactions.delete(first)}const sender=s.players.find(p=>p.id===reaction.playerId);const pop=$('reactionPop');if(!pop)return;pop.innerHTML=`<span>${esc(reaction.emoji)}</span><div><b>${esc(sender?.name||'Player')}</b><small>SENT A REACTION</small></div>`;pop.classList.remove('show');void pop.offsetWidth;pop.classList.add('show');clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>pop.classList.remove('show'),2600);if(reaction.playerId!==myId){tone(490,.07,'triangle');haptic(10)}}
function renderNewReactions(s){const reactions=s.reactions||[];if(!reactions.length)return;for(const reaction of reactions)showReaction(reaction,s)}
function showPhrase(message,s){if(!message||seenPhrases.has(message.id))return;seenPhrases.add(message.id);if(seenPhrases.size>80){const first=seenPhrases.values().next().value;seenPhrases.delete(first)}const sender=s.players.find(p=>p.id===message.playerId);const pop=$('phrasePop');if(!pop)return;pop.innerHTML=`<b>${esc(sender?.name||'Player')} SAYS</b><strong>${esc(message.phrase)}</strong>`;pop.classList.remove('show');void pop.offsetWidth;pop.classList.add('show');clearTimeout(phraseTimer);phraseTimer=setTimeout(()=>pop.classList.remove('show'),3000);if(message.playerId!==myId){tone(610,.09,'triangle');setTimeout(()=>tone(760,.08,'triangle'),90);haptic(14)}}
function renderNewPhrases(s){for(const message of (s.phrases||[]))showPhrase(message,s)}
function openPhraseTray(){const tray=$('phraseTray'),me=state?.players?.find(p=>p.id===myId);const phrases=[...QUICK_PHRASES];if((me?.name||'').trim().toLowerCase()==='becca')phrases.push(BECCA_PHRASE);tray.innerHTML=phrases.map(phrase=>`<button data-phrase="${esc(phrase)}" class="${phrase===BECCA_PHRASE?'becca-phrase':''}">${esc(phrase)}</button>`).join('');$('reactionTray').classList.add('hidden');tray.classList.toggle('hidden')}

function statusText(s,myTurn){if(s.pendingAction){const c=s.players.find(p=>p.id===s.pendingAction.chooserId);return[c?.id===myId?`CHOOSE A TARGET FOR ${actionName(s.pendingAction.card.name)}`:`${c?.name} IS CHOOSING A TARGET`,'Action card in play']}if(s.phase==='lobby')return[`WAITING FOR PLAYERS (${s.players.length}/9)`,'Share the room code to invite friends'];if(s.phase==='playing')return[myTurn?'YOUR DECISION — FLIP OR STAY':`${s.players[s.turnIndex]?.name}'S TURN`,myTurn?'How far will you push it?':'Watch the table'];if(s.phase==='roundEnd')return['ROUND COMPLETE','Scores have been banked'];return[`${s.winner} WINS!`,'Game complete']}
function render(s){const previous=state;state=s;$('copyCode').querySelector('b').textContent=s.code;$('round').textContent=s.round;$('deckCount').textContent=s.deckCount;const me=s.players.find(p=>p.id===myId),turn=s.players[s.turnIndex],myTurn=s.phase==='playing'&&!s.pendingAction&&turn?.id===myId;
$('players').innerHTML='';s.players.forEach((p,i)=>{const e=document.createElement('div');e.className='player '+(s.phase==='playing'&&!s.pendingAction&&i===s.turnIndex?'turn ':'')+(p.voiceEnabled?'voice-on ':'')+(p.voiceSpeaking?'voice-speaking':'');e.dataset.playerId=p.id;const live=p.busted?'BUSTED':p.frozen?`FROZEN ${p.roundScore}`:p.stayed?`BANKED ${p.roundScore}`:`${p.cards.length} NUMBERS`;const reaction=latestReactionFor(s,p.id);e.innerHTML=`<span class="dot ${p.connected?'':'off'}"></span>${reaction?`<div class="player-reaction">${esc(reaction.emoji)}</div>`:''}<div class="avatar" style="background:${avatarColors[i%avatarColors.length]}">${esc(p.name.charAt(0).toUpperCase())}</div><div class="name">${esc(p.name)}${p.id===s.hostId?' ★':''}${i===s.dealerIndex?' ◇':''}</div><div class="score">${p.score}</div><small>${live}${p.second?' · 2ND CHANCE':''}</small>`;$('players').appendChild(e)});
const area=$('myArea'),oldMe=previous?.players?.find(p=>p.id===myId);if(me)renderHand(area,me,oldMe);else{area.innerHTML='';area.dataset.handSig=''}renderOpponentTable(s,previous);renderVoiceSeatStates(s);$('scorePreview').querySelector('b').textContent=calculatePreview(me);
renderTargetPicker(s);$('hit').disabled=!myTurn;$('stay').disabled=!myTurn||!(me&&(me.cards.length||me.mods.length||me.second));$('hit').classList.toggle('hidden',s.phase!=='playing'||!!s.pendingAction);$('stay').classList.toggle('hidden',s.phase!=='playing'||!!s.pendingAction);$('start').classList.toggle('hidden',!(s.phase==='lobby'&&s.hostId===myId));$('next').classList.toggle('hidden',!(s.phase==='roundEnd'&&s.hostId===myId));$('lobbyCard').classList.toggle('hidden',s.phase!=='lobby');$('table').classList.toggle('hidden',s.phase==='lobby');
const [big,small]=statusText(s,myTurn);$('status').innerHTML=`<span class="pulse"></span><b>${esc(big)}</b><small>${esc(small)}</small>`;$('log').innerHTML=s.log.map(x=>`<div>${esc(x)}</div>`).join('');
renderNewReactions(s);renderNewPhrases(s);syncVoicePeers(s);
if(previous){const newCount=(me?.cards.length||0)+(me?.mods.length||0)+(me?.second?1:0),oldCount=(oldMe?.cards.length||0)+(oldMe?.mods.length||0)+(oldMe?.second?1:0);if(newCount>oldCount){tone(680,.08,'triangle');haptic(12)}if(previous.phase!=='gameOver'&&s.phase==='gameOver'){confetti();tone(740,.3);setTimeout(()=>tone(980,.35),180)}}lastPhase=s.phase}
function showModal(html,mode=''){$('modalBody').innerHTML=html;$('modal').classList.remove('hidden');if(mode==='leave')setTimeout(()=>{const b=$('confirmLeave');if(b)b.onclick=leave},0)}
function closeModal(){$('modal').classList.add('hidden')}
$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()}
const help=`<h2>How to play</h2><p>Build the highest score without revealing a duplicate number.</p><ol><li>On your turn, choose <b>Flip</b> to draw or <b>Stay</b> to bank your round value.</li><li>A duplicate number busts your round unless a Second Chance protects you. You may hold only one Second Chance; if you draw another, give it to another active player who does not have one, or discard it if nobody can receive it.</li><li>Second Chance protects only against a duplicate Number card. It does not block Freeze.</li><li>Freeze and Flip Three may target any active player, including yourself.</li><li>During Flip Three, all three revealed cards count unless the target busts or reaches Flip 7. A Second Chance resolves immediately; other Action cards wait until the three-card sequence finishes.</li><li>Seven unique Number cards immediately end the round and award a 15-point bonus. ×2 doubles only the Number-card subtotal; additive modifiers and the +15 bonus are added afterward.</li><li>Once the high score is at least 200, the highest total wins. If the highest score is tied, everyone plays another full round.</li><li>In multiplayer, tap the microphone button to join voice chat. It starts muted and only broadcasts after you grant microphone permission and turn it on.</li></ol><button class="menu-action" onclick="document.getElementById('modal').classList.add('hidden')">GOT IT</button>`;
$('howBtn').onclick=()=>showModal(help);$('menuBtn').onclick=()=>showModal(`<h2>Game menu</h2><button class="menu-action" id="menuHow">HOW TO PLAY</button><button class="menu-action" id="menuSound">${soundOn?'MUTE SOUND':'TURN SOUND ON'}</button><button class="menu-action" id="menuLeave">LEAVE ROOM</button>`);$('modalBody').addEventListener('click',e=>{if(e.target.id==='menuHow')showModal(help);if(e.target.id==='menuSound'){soundOn=!soundOn;localStorage.fr7sound=soundOn?'on':'off';toast(soundOn?'Sound on':'Sound muted');closeModal()}if(e.target.id==='menuLeave')leave()});
$('soundBtn').onclick=()=>{soundOn=!soundOn;localStorage.fr7sound=soundOn?'on':'off';$('soundBtn').textContent=soundOn?'♪':'×';if(soundOn)tone(520,.08)};$('soundBtn').textContent=soundOn?'♪':'×';
$('micBtn').onclick=toggleVoice;updateMicButton();window.addEventListener('pagehide',voicePageHide);
$('react').onclick=()=>{haptic(8);$('phraseTray').classList.add('hidden');$('reactionTray').classList.toggle('hidden')};$('reactionTray').onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.id==='phraseMenuBtn'){haptic(8);openPhraseTray();return}const emoji=button.dataset.emoji;if(!emoji)return;$('reactionTray').classList.add('hidden');haptic(8);api('react',{emoji}).then(()=>{toast(`${emoji} sent to everyone`);tone(420,.05)}).catch(err=>toast(err.message))};$('phraseTray').onclick=e=>{const button=e.target.closest('button[data-phrase]');if(!button)return;const phrase=button.dataset.phrase;$('phraseTray').classList.add('hidden');haptic(8);api('phrase',{phrase}).then(()=>{toast('Phrase sent to everyone');tone(520,.06)}).catch(err=>toast(err.message))};
if(room&&myId){enter();api('state').catch(()=>{localStorage.removeItem('fr7room');localStorage.removeItem('fr7pid');location.reload()})}
setInterval(()=>{if(room&&myId)api('state').catch(()=>{})},800);window.addEventListener('resize',()=>{const area=$('myArea');if(area)fitPlayerHand(area)});
