import http from 'http';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';

const __dirname=path.dirname(fileURLToPath(import.meta.url)), PORT=process.env.PORT||3000, rooms=new Map();
const send=(res,code,obj,type='application/json')=>{res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(type==='application/json'?JSON.stringify(obj):obj)};
const parse=req=>new Promise(resolve=>{let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{resolve(JSON.parse(body||'{}'))}catch{resolve({})}})});
const uid=()=>crypto.randomUUID(), roomCode=()=>crypto.randomBytes(3).toString('hex').toUpperCase();
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makeDeck(){let d=[{type:'number',value:0,id:'n0'}];for(let v=1;v<=12;v++)for(let c=0;c<v;c++)d.push({type:'number',value:v,id:`n${v}-${c}`});for(const n of ['freeze','flip3','second'])for(let c=0;c<3;c++)d.push({type:'action',name:n,id:`${n}-${c}`});for(const v of [2,4,6,8,10])d.push({type:'modifier',value:v,id:`m${v}`});d.push({type:'multiplier',value:2,id:'x2'});return shuffle(d)}
function makePlayer(id,name){return{id,name:String(name||'Player').slice(0,18),score:0,cards:[],mods:[],statusCards:[],active:true,stayed:false,busted:false,frozen:false,second:false,roundScore:0,lastSeen:Date.now()}}
function score(p){if(p.busted)return 0;let n=p.cards.reduce((s,c)=>s+c.value,0);if(p.mods.some(c=>c.type==='multiplier'))n*=2;n+=p.mods.filter(c=>c.type==='modifier').reduce((s,c)=>s+c.value,0);if(p.cards.length>=7)n+=15;return n}
const active=r=>r.players.filter(p=>p.active), byId=(r,id)=>r.players.find(p=>p.id===id), cur=r=>r.players[r.turnIndex];
function replenish(r){if(!r.deck.length&&r.discard.length){r.deck=shuffle(r.discard.splice(0));r.log.push('Discard pile reshuffled.')}} function take(r){replenish(r);return r.deck.pop()||null}
function discardPlayer(r,p){r.discard.push(...p.cards,...p.mods,...p.statusCards);const sc=r.heldSecond.get(p.id);if(sc)r.discard.push(sc);r.heldSecond.delete(p.id)}
function finish(r,reason='Round complete.'){if(r.phase!=='playing')return;r.phase='roundEnd';r.pendingAction=null;for(const p of r.players){p.roundScore=score(p);p.score+=p.roundScore;p.active=false;discardPlayer(r,p)}r.log.push(reason);const high=Math.max(...r.players.map(p=>p.score)),leaders=r.players.filter(p=>p.score===high);if(high>=200&&leaders.length===1){r.phase='gameOver';r.winner=leaders[0].name;r.log.push(`${r.winner} wins with ${high} points!`)}else if(high>=200){r.log.push(`The game is tied at ${high}. Everyone plays another full round.`)}r.dealerIndex=(r.dealerIndex+1)%r.players.length}
function checkEnd(r){if(r.phase!=='playing')return true;if(active(r).length===0){finish(r);return true}return false}
function advance(r){if(checkEnd(r))return;for(let i=0;i<r.players.length;i++){r.turnIndex=(r.turnIndex+1)%r.players.length;if(cur(r)?.active)return}}
function resume(r,x){if(r.phase!=='playing'||!x)return;if(x.type==='deal')initial(r,x.next);else if(x.type==='turn')advance(r);else if(x.type==='flip3')flipThree(r,x.targetId,x.remaining,x.queue||[],x.after);else if(x.type==='queue')resolveQueue(r,x.queue||[],x.after)}
function grantSecond(r,p,card,resumeTo){if(!p?.active){r.discard.push(card);resume(r,resumeTo);return}if(!p.second){p.second=true;r.heldSecond.set(p.id,card);r.log.push(`${p.name} kept a Second Chance.`);resume(r,resumeTo);return}
 const eligible=active(r).filter(x=>x.id!==p.id&&!x.second);
 if(!eligible.length){r.discard.push(card);r.log.push(`${p.name} drew an extra Second Chance; every active player already has one, so it was discarded.`);resume(r,resumeTo);return}
 r.pendingAction={kind:'secondTransfer',chooserId:p.id,card,resume:resumeTo,eligibleIds:eligible.map(x=>x.id)};
 r.log.push(`${p.name} must give the extra Second Chance to an active player without one.`)}
function offerAction(r,chooserId,card,resumeTo){if(card.name==='second')return grantSecond(r,byId(r,chooserId),card,resumeTo);const eligible=active(r);if(!eligible.length){r.discard.push(card);resume(r,resumeTo);return}r.pendingAction={kind:card.name,chooserId,card,resume:resumeTo,eligibleIds:eligible.map(p=>p.id)};r.log.push(`${byId(r,chooserId).name} drew ${card.name==='freeze'?'Freeze':'Flip Three'} and must choose a target.`)}
function resolveNumber(r,p,c){const dup=p.cards.some(x=>x.value===c.value);if(dup&&p.second){p.second=false;const sc=r.heldSecond.get(p.id);if(sc)r.discard.push(sc);r.heldSecond.delete(p.id);r.discard.push(c);r.log.push(`${p.name}'s Second Chance prevented duplicate ${c.value}.`);return'safe'}p.cards.push(c);if(dup){p.busted=true;p.active=false;r.log.push(`${p.name} busted on ${c.value}!`);return'bust'}r.log.push(`${p.name} flipped ${c.value}.`);if(p.cards.length>=7){finish(r,`${p.name} reached Flip 7 and ended the round!`);return'flip7'}return'safe'}
function nonAction(r,p,c){if(c.type==='number')return resolveNumber(r,p,c);p.mods.push(c);r.log.push(`${p.name} gained ${c.type==='multiplier'?'×2':'+'+c.value}.`);return'safe'}
function drawTurn(r,p){const c=take(r);if(!c)return finish(r,'Deck exhausted.');if(c.type!=='action'){nonAction(r,p,c);if(r.phase==='playing')advance(r)}else offerAction(r,p.id,c,{type:'turn'})}
function initial(r,offset=0){if(r.phase!=='playing')return;if(offset>=r.players.length){r.turnIndex=(r.dealerIndex+1)%r.players.length;while(r.phase==='playing'&&!cur(r)?.active)advance(r);return}const i=(r.dealerIndex+1+offset)%r.players.length,p=r.players[i],c=take(r);if(!c)return finish(r,'Deck exhausted.');if(c.type==='action')offerAction(r,p.id,c,{type:'deal',next:offset+1});else{nonAction(r,p,c);if(r.phase==='playing')initial(r,offset+1)}}
function applyTarget(r,pending,targetId){const chooser=byId(r,pending.chooserId),target=byId(r,targetId),card=pending.card,resumeTo=pending.resume;r.pendingAction=null;
 if(pending.kind==='secondTransfer'){target.second=true;r.heldSecond.set(target.id,card);r.log.push(`${chooser.name} gave the extra Second Chance to ${target.name}.`);resume(r,resumeTo);return}
 r.discard.push(card);
 if(pending.kind==='freeze'){r.discard.pop();target.statusCards.push(card);target.frozen=true;target.stayed=true;target.active=false;target.roundScore=score(target);r.log.push(`${chooser.name} froze ${target.name} at ${target.roundScore} points.`);if(!checkEnd(r))resume(r,resumeTo);return}
 r.log.push(`${chooser.name} played Flip Three on ${target.name}.`);flipThree(r,target.id,3,[],resumeTo)}
function flipThree(r,targetId,remaining,queue,after){if(r.phase!=='playing')return;const p=byId(r,targetId);if(!p?.active||remaining<=0)return resolveQueue(r,queue,after);const c=take(r);if(!c)return finish(r,'Deck exhausted.');if(c.type!=='action'){const result=nonAction(r,p,c);if(r.phase!=='playing'||result!=='safe')return;return flipThree(r,targetId,remaining-1,queue,after)}if(c.name==='second')return grantSecond(r,p,c,{type:'flip3',targetId,remaining:remaining-1,queue,after});queue.push({chooserId:targetId,card:c});r.log.push(`${p.name} revealed ${c.name==='freeze'?'Freeze':'Flip Three'} during Flip Three; it will resolve after the three-card sequence.`);flipThree(r,targetId,remaining-1,queue,after)}
function resolveQueue(r,q,after){if(r.phase!=='playing')return;if(!q.length)return resume(r,after);const [n,...rest]=q,chooser=byId(r,n.chooserId);if(!chooser?.active){r.discard.push(n.card);return resolveQueue(r,rest,after)}offerAction(r,chooser.id,n.card,{type:'queue',queue:rest,after})}
function startRound(r){r.round++;r.phase='playing';r.pendingAction=null;r.winner=null;r.players.forEach(p=>Object.assign(p,{cards:[],mods:[],statusCards:[],active:true,stayed:false,busted:false,frozen:false,second:false,roundScore:0}));r.heldSecond.clear();if(!r.deck.length)r.deck=makeDeck();r.log=[`Round ${r.round} begins.`];initial(r,0)}
function state(r){return{code:r.code,hostId:r.hostId,phase:r.phase,round:r.round,turnIndex:r.turnIndex,dealerIndex:r.dealerIndex,deckCount:r.deck.length,pendingAction:r.pendingAction?{kind:r.pendingAction.kind,chooserId:r.pendingAction.chooserId,card:r.pendingAction.card,eligibleIds:r.pendingAction.eligibleIds}:null,players:r.players.map(p=>({...p,connected:Date.now()-p.lastSeen<12000})),log:r.log.slice(-25),winner:r.winner,reaction:r.reaction}}
const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.json':'application/json'};
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/health')return send(res,200,{ok:true});if(u.pathname.startsWith('/api/')){const body=req.method==='POST'?await parse(req):{};
 if(u.pathname==='/api/create'){let code=roomCode();while(rooms.has(code))code=roomCode();const id=uid(),r={code,hostId:id,phase:'lobby',round:0,turnIndex:0,dealerIndex:0,players:[makePlayer(id,body.name||'Host')],deck:makeDeck(),discard:[],heldSecond:new Map(),pendingAction:null,log:['Room created.'],winner:null,reaction:null};rooms.set(code,r);return send(res,200,{ok:true,room:code,playerId:id,state:state(r)})}
 if(u.pathname==='/api/join'){const r=rooms.get(String(body.room||'').toUpperCase());if(!r)return send(res,404,{ok:false,error:'Room not found.'});if(r.phase!=='lobby')return send(res,400,{ok:false,error:'Game already started.'});if(r.players.length>=9)return send(res,400,{ok:false,error:'This room is full (official limit: 9 players).'});const id=uid(),p=makePlayer(id,body.name);r.players.push(p);return send(res,200,{ok:true,room:r.code,playerId:id,state:state(r)})}
 const code=String(body.room||u.searchParams.get('room')||'').toUpperCase(),r=rooms.get(code);if(!r)return send(res,404,{ok:false,error:'Room not found.'});const id=body.playerId||u.searchParams.get('playerId'),p=byId(r,id);if(p)p.lastSeen=Date.now();if(u.pathname==='/api/state')return send(res,200,{ok:true,state:state(r)});if(!p)return send(res,403,{ok:false,error:'Player not found.'});
 if(u.pathname==='/api/start'){if(r.hostId!==id||r.players.length<3)return send(res,400,{ok:false,error:'Only the host can start, with 3–9 players.'});startRound(r)}
 else if(u.pathname==='/api/hit'){if(r.phase!=='playing'||r.pendingAction||cur(r)?.id!==id)return send(res,400,{ok:false,error:'It is not your turn.'});drawTurn(r,p)}
 else if(u.pathname==='/api/stay'){if(r.phase!=='playing'||r.pendingAction||cur(r)?.id!==id)return send(res,400,{ok:false,error:'It is not your turn.'});if(!p.cards.length&&!p.mods.length&&!p.second)return send(res,400,{ok:false,error:'You need at least one card before staying.'});p.stayed=true;p.active=false;p.roundScore=score(p);r.log.push(`${p.name} stayed with ${p.roundScore}.`);advance(r)}
 else if(u.pathname==='/api/target'){const a=r.pendingAction;if(!a||a.chooserId!==id||!a.eligibleIds.includes(body.targetId))return send(res,400,{ok:false,error:'Invalid target.'});applyTarget(r,a,body.targetId)}
 else if(u.pathname==='/api/react'){const emojis=['😂','😮','😭','😡','👍','👏'];const phrases=['You suck!','You’re a peckerhead!','You got lucky!','So close','Tough Break!'];const kind=body.kind,value=String(body.value||'');if(kind!=='emoji'&&kind!=='phrase')return send(res,400,{ok:false,error:'Invalid reaction.'});if(kind==='emoji'&&!emojis.includes(value))return send(res,400,{ok:false,error:'Invalid emoticon.'});if(kind==='phrase'&&!phrases.includes(value))return send(res,400,{ok:false,error:'Invalid phrase.'});r.reaction={id:uid(),kind,value,playerId:p.id,playerName:p.name,ts:Date.now()}} else if(u.pathname==='/api/next'){if(r.hostId!==id||r.phase!=='roundEnd')return send(res,400,{ok:false,error:'Only the host can start the next round.'});startRound(r)}
 else return send(res,404,{ok:false,error:'Unknown action.'});return send(res,200,{ok:true,state:state(r)})}
 let f=u.pathname==='/'?'/index.html':u.pathname;f=path.join(__dirname,f);fs.readFile(f,(e,d)=>e?send(res,404,'Not found','text/plain'):send(res,200,d,mime[path.extname(f)]||'application/octet-stream'))});
server.listen(PORT,'0.0.0.0',()=>console.log(`Flip Rush 7 running on ${PORT}`));